% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  11pt,
  a4paper,
  oneside,
  openany]{article}

\usepackage{amsmath,amssymb}
\usepackage{setspace}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage[]{libertine}
\ifPDFTeX\else
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[top=30mm,left=25mm,right=25mm,bottom=30mm,heightrounded,top=25mm,bottom=25mm]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{5}
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{float}
\usepackage{placeins}
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[skins,breakable]{tcolorbox}}
\@ifpackageloaded{fontawesome5}{}{\usepackage{fontawesome5}}
\definecolor{quarto-callout-color}{HTML}{909090}
\definecolor{quarto-callout-note-color}{HTML}{0758E5}
\definecolor{quarto-callout-important-color}{HTML}{CC1914}
\definecolor{quarto-callout-warning-color}{HTML}{EB9113}
\definecolor{quarto-callout-tip-color}{HTML}{00A047}
\definecolor{quarto-callout-caution-color}{HTML}{FC5300}
\definecolor{quarto-callout-color-frame}{HTML}{acacac}
\definecolor{quarto-callout-note-color-frame}{HTML}{4582ec}
\definecolor{quarto-callout-important-color-frame}{HTML}{d9534f}
\definecolor{quarto-callout-warning-color-frame}{HTML}{f0ad4e}
\definecolor{quarto-callout-tip-color-frame}{HTML}{02b875}
\definecolor{quarto-callout-caution-color-frame}{HTML}{fd7e14}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\captionsetup{labelsep=colon}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\ifLuaTeX
\usepackage[bidi=basic]{babel}
\else
\usepackage[bidi=default]{babel}
\fi
\babelprovide[main,import]{american}
% get rid of language-specific shorthands (see #6817):
\let\LanguageShortHands\languageshorthands
\def\languageshorthands#1{}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Astro-Seismology of the Indian Subcontinent: Statistical Validation of Planetary Triggers for Earthquake Prediction},
  pdflang={en-US},
  pdfkeywords={Earthquake Prediction, India-Nepal Seismicity, Vedic
Astrology, Negative Binomial Regression, Monte Carlo
Validation, Shadbala, USGS Data},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={green},
  urlcolor={blue},
  pdfcreator={LaTeX via pandoc}}

\title{Astro-Seismology of the Indian Subcontinent: Statistical
Validation of Planetary Triggers for Earthquake Prediction}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{A Rigorous Investigation Using Negative Binomial Regression
and Monte Carlo Methods on India-Nepal Seismic Data (2015-2024)}
\author{Astro-Fusion Research Team}
\date{February 20, 2026}

\begin{document}
\maketitle
\begin{abstract}
This research track investigates the empirical potential for
astrological prediction of seismic activity within the India-Nepal
Tectonic Zone, one of Earth's most seismically active regions. Using
data from 370 significant earthquakes (Magnitude ≥ 4.5) recorded by the
USGS Earthquake Hazards Program between 2015-2024, we develop and test a
``Planetary Stress Index'' derived from Vedic Astrology principles
including Shadbala (six-fold planetary strength), Graha Yuddha
(planetary wars), and malefic aspects. Employing Negative Binomial
regression to account for overdispersion in earthquake counts, and Monte
Carlo permutation testing to establish empirical null distributions, we
subject the hypothesis to rigorous ``Severe Testing'' criteria. Our
results indicate that planetary variables fail to achieve statistical
significance (Mars p=0.10, Saturn p=0.99) when predicting earthquake
occurrence, with Monte Carlo validation confirming that observed signals
fall within the random noise distribution. We conclude that planetary
configurations, as operationalized through classical Vedic techniques,
do not provide reliable predictive power for seismic events in the
tested region.
\end{abstract}

\renewcommand*\contentsname{Table of contents}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{3}
\tableofcontents
}
\listoffigures
\listoftables
\setstretch{1.2}
\section{Master Structure}\label{master-structure}

\begin{tcolorbox}[enhanced jigsaw, bottomtitle=1mm, rightrule=.15mm, leftrule=.75mm, colbacktitle=quarto-callout-note-color!10!white, colframe=quarto-callout-note-color-frame, coltitle=black, titlerule=0mm, opacityback=0, colback=white, left=2mm, toptitle=1mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Note}, breakable, toprule=.15mm, bottomrule=.15mm, opacitybacktitle=0.6, arc=.35mm]

This report is assembled from modular sections for maintainability.

\end{tcolorbox}

\section{Overview}\label{overview}

This report provides an \textbf{exhaustive Classical Jyotish Mundane}
coverage for earthquake prediction claims. The intent is to
\textbf{include every combination and trigger described in the classical
corpus} so the analysis cannot be dismissed for missing principles. The
report is organized as a modular catalogue, followed by algorithmic
definitions and a large-scale empirical evaluation against the
India-Nepal seismic dataset.

\subsection{Scope Commitments}\label{scope-commitments}

\begin{itemize}
\tightlist
\item
  \textbf{All Classical Sources}: Brihat Samhita, BPHS, Surya Siddhanta,
  Jataka Parijata, Saravali.
\item
  \textbf{All Combination Classes}: malefic aspects, conjunctions, Graha
  Yuddha, Shadbala components, combustion, retrograde, nakshatra lords,
  Panchanga elements (tithi/karana/yoga), houses and signs, eclipses and
  syzygy windows.
\item
  \textbf{All Time Windows}: same-day, ±1, ±3, ±7, ±14, ±30 days around
  seismic events.
\item
  \textbf{All Results Reported}: frequency, event-alignment rate, and
  statistical significance where applicable.
\end{itemize}

\subsection{Structure}\label{structure}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Sources}: Classical texts and canonical principles.
\item
  \textbf{Taxonomy}: A formal ontology of all trigger classes and
  variables.
\item
  \textbf{Combination Catalog}: Machine-generated, exhaustive list with
  stable IDs.
\item
  \textbf{Algorithms \& Examples}: Formal definitions and step-by-step
  calculations.
\item
  \textbf{Graphs \& Results}: Frequency and alignment diagnostics for
  every category.
\item
  \textbf{Appendix}: Full definitions and parameter defaults.
\end{enumerate}

\section{Classical Sources}\label{classical-sources}

This section enumerates the authoritative classical sources used as
\textbf{primary references} for mundane astrology principles included in
this report.

\subsection{Covered Sources (Primary
Canon)}\label{covered-sources-primary-canon}

\begin{itemize}
\tightlist
\item
  \textbf{Brihat Samhita} (Varahamihira c. 6th century CE)
\item
  \textbf{Brihat Parashara Hora Shastra (BPHS)} (Parashara c. 7th
  century CE)
\item
  \textbf{Surya Siddhanta} (Anonymous c. 4th century CE)
\item
  \textbf{Jataka Parijata} (Dikshita c. 14th century CE)
\item
  \textbf{Saravali} (Varma c. 8th century CE)
\end{itemize}

\subsection{Coverage Policy}\label{coverage-policy}

All mundane principles that can be translated into \textbf{testable
astronomical combinations} are included. If a classical rule is symbolic
or qualitative, it is still recorded in the catalog with a note
describing the limitation.

\section{Vedic Principles Coverage (Master
Catalog)}\label{vedic-principles-coverage-master-catalog}

This report anchors its methodology in a shared \textbf{Vedic Principles
Catalog} derived from classical Jyotish sources. Every computable
principle is enumerated and mapped to a reproducible algorithm;
non-computable rules are still documented to maintain completeness and
avoid selective omission. (Parashara c. 7th century CE; Varahamihira c.
6th century CE; Varma c. 8th century CE; Dikshita c. 14th century CE;
Anonymous c. 4th century CE)

\begin{figure}[H]

\caption{Vedic Principles Catalog: Counts by Family}

{\centering \includegraphics{EARTHQUAKE_PREDICTION_INDIA_NEPAL_ANALYSIS_files/figure-pdf/eq-vedic-catalog-counts-output-1.png}

}

\end{figure}%

\begin{longtable}[]{@{}lllllll@{}}

\caption{\label{tbl-eq-vedic-coverage}Coverage Matrix for Earthquake
Report}

\tabularnewline

\toprule\noalign{}
coverage\_status & family & scope & computed & documented &
not\_included & coverage\_ratio \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
3 & bhava & core & 13 & 0 & 0 & 1.0 \\
4 & combustion & core & 1 & 0 & 0 & 1.0 \\
6 & dignity & core & 0 & 0 & 1 & 0.0 \\
7 & drishti & core & 1 & 0 & 0 & 1.0 \\
8 & eclipse & core & 1 & 0 & 0 & 1.0 \\
10 & graha & core & 10 & 0 & 0 & 1.0 \\
11 & graha\_yuddha & core & 1 & 0 & 0 & 1.0 \\
13 & karana & core & 12 & 0 & 0 & 1.0 \\
15 & nakshatra & core & 28 & 0 & 0 & 1.0 \\
16 & rashi & core & 13 & 0 & 0 & 1.0 \\
17 & retrograde & core & 1 & 0 & 0 & 1.0 \\
18 & shadbala & core & 1 & 0 & 0 & 1.0 \\
19 & syzygy & core & 1 & 0 & 0 & 1.0 \\
20 & tithi & core & 31 & 0 & 0 & 1.0 \\
23 & yoga & core & 28 & 0 & 0 & 1.0 \\
0 & arudha & extended & 0 & 3 & 0 & 0.0 \\
1 & ashtakavarga & extended & 0 & 3 & 0 & 0.0 \\
2 & avastha & extended & 0 & 7 & 0 & 0.0 \\
5 & dasha & extended & 6 & 0 & 0 & 1.0 \\
9 & gocara & extended & 0 & 1 & 0 & 0.0 \\
12 & kala & extended & 0 & 1 & 0 & 0.0 \\
14 & muhurta & extended & 0 & 1 & 0 & 0.0 \\
21 & upagraha & extended & 0 & 6 & 0 & 0.0 \\
22 & varga & extended & 0 & 17 & 0 & 0.0 \\
24 & yoga\_classical & extended & 0 & 1 & 0 & 0.0 \\

\end{longtable}

\begin{longtable}[]{@{}lllllll@{}}

\caption{\label{tbl-eq-vedic-master}Master Vedic Principles Catalog
(Core + Extended)}

\tabularnewline

\toprule\noalign{}
& family & item\_type & name & scope & computable & description \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & arudha & family & Arudha (Pada) & extended & False &
Reflection-based indicators of manifestation a... \\
1 & arudha & member & Arudha Lagna & extended & False & Arudha concept:
Arudha Lagna. \\
2 & arudha & member & Bhava Arudha & extended & False & Arudha concept:
Bhava Arudha. \\
3 & ashtakavarga & family & Ashtakavarga & extended & False &
Point-based evaluation of planetary contributi... \\
4 & ashtakavarga & member & Bhinnashtakavarga & extended & False &
Ashtakavarga method: Bhinnashtakavarga. \\
... & ... & ... & ... & ... & ... & ... \\
184 & yoga & member & Vishkumbha & core & True & Yoga: Vishkumbha. \\
185 & yoga & member & Vriddhi & core & True & Yoga: Vriddhi. \\
186 & yoga & member & Vyaghata & core & True & Yoga: Vyaghata. \\
187 & yoga & member & Vyatipata & core & True & Yoga: Vyatipata. \\
188 & yoga\_classical & family & Classical Yogas & extended & False &
Combinational yogas such as Raja, Dhana, and A... \\

\end{longtable}

\section{Mundane Jyotish Taxonomy (Exhaustive
Scope)}\label{mundane-jyotish-taxonomy-exhaustive-scope}

This section defines the \textbf{complete combination space} used in the
report. All combinations are derived from the canonical sources listed
in Section 1 and formalized into a machine-readable taxonomy.

\subsection{Core Entities}\label{core-entities}

\begin{itemize}
\tightlist
\item
  \textbf{Planets (Grahas)}: Sun, Moon, Mars, Mercury, Jupiter, Venus,
  Saturn, Rahu, Ketu.
\item
  \textbf{Lunar Elements}: Tithi, Nakshatra, Karana, Yoga.
\item
  \textbf{Houses (Bhavas)}: 1--12 with emphasis on 4th (land), 8th
  (catastrophe), 12th (loss).
\item
  \textbf{Signs (Rashi)}: 12 zodiac signs (sidereal).
\item
  \textbf{Angular Relations}: Conjunction (0°), square (90°), opposition
  (180°), trine (120°), sextile (60°).
\item
  \textbf{Temporal Windows}: \{0, ±1, ±3, ±7, ±14, ±30\} days.
\end{itemize}

\subsection{Combination Classes (All
Included)}\label{combination-classes-all-included}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Malefic Aspects}: Mars/Saturn/Rahu/Ketu hard aspects.
\item
  \textbf{Graha Yuddha}: Close conjunctions (\textless1°) between any
  pair.
\item
  \textbf{Shadbala Components}: Each component and total combined
  strength.
\item
  \textbf{Combustion \& Retrograde}: Planet visibility and motion
  states.
\item
  \textbf{Eclipses \& Syzygy}: Solar/lunar eclipses; new/full moon
  windows.
\item
  \textbf{Nakshatra Lords}: Lunar mansion rulerships and transitions.
\item
  \textbf{House/Sign Triggers}: Malefics in critical houses or signs.
\item
  \textbf{Panchanga}: Tithi/Karana/Yoga combinations.
\item
  \textbf{Compound Rules}: Multi-factor conjunctions (e.g., Mars+Saturn
  conjunction during eclipse window in 4th house).
\end{enumerate}

\subsection{Ontology Fields (Catalog
Columns)}\label{ontology-fields-catalog-columns}

\begin{longtable}[]{@{}ll@{}}
\toprule\noalign{}
Field & Description \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\texttt{combo\_id} & Stable unique ID \\
\texttt{category} & Combination class \\
\texttt{rule} & Formal rule definition \\
\texttt{window\_days} & Event window \\
\texttt{sources} & Classical references \\
\texttt{parameters} & Orbs, thresholds, rule-specific values \\
\end{longtable}

\subsection{Formal Notation}\label{formal-notation}

\begin{itemize}
\tightlist
\item
  \textbf{Planetary longitude}: \(\lambda_p(t)\)
\item
  \textbf{Aspect condition}:
  \(|\lambda_i - \lambda_j| \in \{0°, 60°, 90°, 120°, 180°\} \pm \epsilon\)
\item
  \textbf{Conjunction (Graha Yuddha)}: \(|\lambda_i - \lambda_j| < 1°\)
\item
  \textbf{Combustion}: \(|\lambda_p - \lambda_{Sun}| < 8°\)
\item
  \textbf{Retrograde}: \(\dot{\lambda}_p(t) < 0\)
\end{itemize}

\subsection{Combination Explosion
Control}\label{combination-explosion-control}

To ensure ``all combinations'' is \textbf{computationally tractable}, we
define a complete but finite rule system:

\begin{itemize}
\tightlist
\item
  All planet pairs/triples within the rule set.
\item
  All major aspects with configurable orbs.
\item
  All critical houses and signs with malefic occupancy.
\item
  All Panchanga elements for daily classification.
\item
  All defined time windows.
\end{itemize}

The master catalog is generated from these rules, guaranteeing
exhaustive coverage without ambiguity.

\section{Malefics, Aspects, and Angular
Stress}\label{malefics-aspects-and-angular-stress}

Classical mundane astrology emphasizes malefic angular relationships as
destabilizing triggers (Parashara c. 7th century CE; Varahamihira c. 6th
century CE).

\subsection{Malefic Set}\label{malefic-set}

We define malefics as:

\textbf{Mars, Saturn, Rahu, Ketu}

\subsection{Aspect Definitions}\label{aspect-definitions}

All \textbf{major aspects} are included:

\begin{itemize}
\tightlist
\item
  Conjunction (0°)
\item
  Sextile (60°)
\item
  Square (90°)
\item
  Trine (120°)
\item
  Opposition (180°)
\end{itemize}

\subsection{Formal Rule}\label{formal-rule}

For planet pair \((i,j)\) and aspect angle \(\theta\):

\[
|(\lambda_i - \lambda_j) \bmod 360 - \theta| \leq \epsilon
\]

We evaluate all orbs
\(\epsilon \in \{1^\circ, 3^\circ, 5^\circ, 8^\circ\}\).

\subsection{Exhaustive Coverage}\label{exhaustive-coverage}

All malefic--malefic, malefic--benefic, and all-planet pairs are
enumerated in the Master Combination Catalog.

\section{Conjunctions and Graha
Yuddha}\label{conjunctions-and-graha-yuddha}

Classical texts describe \textbf{Graha Yuddha} (planetary war) as a
critical indicator when two planets occupy nearly the same longitude
(Parashara c. 7th century CE).

\subsection{Conjunction Rule}\label{conjunction-rule}

For any planet pair \((i,j)\):

\[
|\lambda_i - \lambda_j| \leq \epsilon
\]

We evaluate conjunctions at multiple orbs, and Graha Yuddha specifically
at \textbf{1°}.

\subsection{Exhaustive Coverage}\label{exhaustive-coverage-1}

All planet pairs are tested. Malefic-only conjunctions are highlighted
as a dedicated subset in the catalog.

\section{Shadbala Components (Sixfold
Strength)}\label{shadbala-components-sixfold-strength}

Shadbala is a composite measure of planetary strength described in
classical Jyotish (Parashara c. 7th century CE). We include each
component and the total aggregated score.

\subsection{Components}\label{components}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Sthana Bala} (positional)
\item
  \textbf{Dig Bala} (directional)
\item
  \textbf{Kala Bala} (temporal)
\item
  \textbf{Chesta Bala} (motional)
\item
  \textbf{Naisargika Bala} (natural)
\item
  \textbf{Drik Bala} (aspectual)
\end{enumerate}

\subsection{Rule Bands}\label{rule-bands}

Each planet is categorized into \textbf{low / medium / high} strength
bands:

\begin{itemize}
\tightlist
\item
  Low: 0--33
\item
  Medium: 34--66
\item
  High: 67--100
\end{itemize}

These bands are applied to \textbf{all planets} daily.

\section{Combustion, Retrograde, and
Visibility}\label{combustion-retrograde-and-visibility}

Combustion and retrograde status are classical modifiers of planetary
efficacy (Parashara c. 7th century CE).

\subsection{Combustion}\label{combustion}

A planet is combust when within a defined orb of the Sun. We use
\textbf{8°} as the standard orb:

\[
|\lambda_p - \lambda_{Sun}| < 8^\circ
\]

\subsection{Retrograde}\label{retrograde}

A planet is retrograde when its longitudinal speed is negative:

\[
\dot{\lambda}_p(t) < 0
\]

All planets are evaluated daily for both conditions.

\section{Vimshottari Dasha Overlay (India +
Nepal)}\label{vimshottari-dasha-overlay-india-nepal}

To address \textbf{phase‑2 country‑specific triggers}, we overlay the
\textbf{India Independence Chart} (1947‑08‑15 00:00 IST, Delhi) and a
\textbf{Nepal reference chart} (2015‑09‑20 00:00 NPT, Kathmandu) and
compute the active \textbf{Vimshottari Mahadasha} for each day in the
earthquake dataset. This allows the analysis to test whether regional
dasha cycles contribute to event clustering beyond the global planetary
configurations. (Parashara c. 7th century CE)

\begin{figure}[H]

\caption{\label{fig-eq-dasha-days}}

\centering{

\captionsetup{labelsep=none}

\subcaption{\label{fig-eq-dasha-days-1}India vs Nepal Vimshottari
Mahadasha: Day Counts}

\centering{

\begin{verbatim}
<Figure size 2100x1200 with 0 Axes>
\end{verbatim}

}

\subcaption{\label{fig-eq-dasha-days-2}}

\centering{

\captionsetup{labelsep=none}\includegraphics{EARTHQUAKE_PREDICTION_INDIA_NEPAL_ANALYSIS_files/figure-pdf/fig-eq-dasha-days-output-2.png}

}

}

\end{figure}%

\begin{figure}[H]

\caption{\label{fig-eq-dasha-timeline}Mahadasha Timeline: India vs Nepal
(2015-2024)}

\centering{

\includegraphics{EARTHQUAKE_PREDICTION_INDIA_NEPAL_ANALYSIS_files/figure-pdf/fig-eq-dasha-timeline-output-1.png}

}

\end{figure}%

\begin{figure}[H]

\caption{\label{fig-eq-dasha-heatmap}Mahadasha Co-Occurrence: India vs
Nepal}

\centering{

\includegraphics{EARTHQUAKE_PREDICTION_INDIA_NEPAL_ANALYSIS_files/figure-pdf/fig-eq-dasha-heatmap-output-1.png}

}

\end{figure}%

\begin{figure}[H]

\caption{\label{fig-eq-antardasha-heatmap}Antardasha Co-Occurrence:
India vs Nepal}

\centering{

\includegraphics{EARTHQUAKE_PREDICTION_INDIA_NEPAL_ANALYSIS_files/figure-pdf/fig-eq-antardasha-heatmap-output-1.png}

}

\end{figure}%

\section{Eclipses, Syzygy, and Temporal
Windows}\label{eclipses-syzygy-and-temporal-windows}

Classical texts emphasize eclipse windows and syzygy as periods of
heightened instability (Anonymous c. 4th century CE; Varahamihira c. 6th
century CE).

\subsection{Syzygy}\label{syzygy}

\begin{itemize}
\tightlist
\item
  \textbf{New Moon (Amavasya)}: \(Tithi = 30\)
\item
  \textbf{Full Moon (Purnima)}: \(Tithi = 15\)
\end{itemize}

\subsection{Eclipse Proxy}\label{eclipse-proxy}

We flag eclipse windows when syzygy coincides with proximity to lunar
nodes (Rahu/Ketu):

\[
\min(|\lambda_{Moon}-\lambda_{Rahu}|, |\lambda_{Moon}-\lambda_{Ketu}|) \leq 12^\circ
\]

\subsection{Windows}\label{windows}

All combinations are evaluated in time windows: \textbf{0, ±1, ±3, ±7,
±14, ±30 days}.

\section{Nakshatra-Based Mundane
Triggers}\label{nakshatra-based-mundane-triggers}

The Moon's Nakshatra lord is used as a daily classifier of cosmic mood
(Parashara c. 7th century CE). We evaluate all \textbf{9 planetary
lords} across the full date range.

\subsection{Rule}\label{rule}

\[
NakshatraLord = f(\lambda_{Moon})
\]

Each Nakshatra is mapped to its classical ruler; all lords are included
in the catalog.

\section{Houses, Signs, and Bhava-Based Mundane
Rules}\label{houses-signs-and-bhava-based-mundane-rules}

Classical mundane astrology associates specific houses with land
stability and catastrophe (Parashara c. 7th century CE). We test
\textbf{all planet-in-house} and \textbf{planet-in-sign} combinations,
with emphasis on critical houses (4, 8, 12).

\subsection{House Occupancy}\label{house-occupancy}

For each planet \(p\):

\[
House(p) = \left\lfloor \frac{(\lambda_p - \lambda_{Asc}) \bmod 360}{30} \right\rfloor + 1
\]

\subsection{Sign Occupancy}\label{sign-occupancy}

Each planet's zodiac sign is derived from its longitude and mapped to
the sidereal sign index.

\subsection{Coverage}\label{coverage}

All planets × all houses and signs are enumerated in the master catalog.

\section{Yogas, Tithi, Karana, and Panchanga
Combinations}\label{yogas-tithi-karana-and-panchanga-combinations}

Panchanga elements are daily time-structure variables derived from
Sun--Moon dynamics (Anonymous c. 4th century CE). All combinations are
included.

\subsection{Tithi}\label{tithi}

\[
Tithi = \left\lfloor \frac{(\lambda_{Moon}-\lambda_{Sun}) \bmod 360}{12} \right\rfloor + 1
\]

\subsection{Karana}\label{karana}

\[
KaranaIndex = \left\lfloor \frac{(\lambda_{Moon}-\lambda_{Sun}) \bmod 360}{6} \right\rfloor + 1
\]

\subsection{Yoga}\label{yoga}

\[
Yoga = \left\lfloor \frac{(\lambda_{Moon}+\lambda_{Sun}) \bmod 360}{13.3333} \right\rfloor + 1
\]

All 30 tithis, 11 karana types, and 27 yogas are enumerated in the
catalog.

\section{Master Combination Catalog}\label{master-combination-catalog}

This section presents the \textbf{exhaustive combination catalog},
generated programmatically from the taxonomy. Each rule has a stable ID
for reproducibility and downstream graphing.

\phantomsection\label{combo-catalog}
\begin{longtable}[]{@{}llllllllllllllllllllll@{}}
\toprule\noalign{}
& combo\_id & category & rule & parameters & window\_days & sources & p1
& p2 & aspect & aspect\_deg & ... & tithi & karana & yoga &
eclipse\_type & phase & lord & sub\_lord & india\_lord & nepal\_lord &
compound \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & aspects:000001 & aspects & Aspect conjunction between Sun and Moon &
angle=0±1° & NaN & Brihat Samhita; BPHS; Surya Siddhanta; Jataka ... &
Sun & Moon & conjunction & 0.0 & ... & NaN & NaN & NaN & NaN & NaN & NaN
& NaN & NaN & NaN & NaN \\
1 & aspects:000002 & aspects & Aspect conjunction between Sun and Moon &
angle=0±3° & NaN & Brihat Samhita; BPHS; Surya Siddhanta; Jataka ... &
Sun & Moon & conjunction & 0.0 & ... & NaN & NaN & NaN & NaN & NaN & NaN
& NaN & NaN & NaN & NaN \\
2 & aspects:000003 & aspects & Aspect conjunction between Sun and Moon &
angle=0±5° & NaN & Brihat Samhita; BPHS; Surya Siddhanta; Jataka ... &
Sun & Moon & conjunction & 0.0 & ... & NaN & NaN & NaN & NaN & NaN & NaN
& NaN & NaN & NaN & NaN \\
3 & aspects:000004 & aspects & Aspect conjunction between Sun and Moon &
angle=0±8° & NaN & Brihat Samhita; BPHS; Surya Siddhanta; Jataka ... &
Sun & Moon & conjunction & 0.0 & ... & NaN & NaN & NaN & NaN & NaN & NaN
& NaN & NaN & NaN & NaN \\
4 & aspects:000005 & aspects & Aspect sextile between Sun and Moon &
angle=60±1° & NaN & Brihat Samhita; BPHS; Surya Siddhanta; Jataka ... &
Sun & Moon & sextile & 60.0 & ... & NaN & NaN & NaN & NaN & NaN & NaN &
NaN & NaN & NaN & NaN \\
5 & aspects:000006 & aspects & Aspect sextile between Sun and Moon &
angle=60±3° & NaN & Brihat Samhita; BPHS; Surya Siddhanta; Jataka ... &
Sun & Moon & sextile & 60.0 & ... & NaN & NaN & NaN & NaN & NaN & NaN &
NaN & NaN & NaN & NaN \\
6 & aspects:000007 & aspects & Aspect sextile between Sun and Moon &
angle=60±5° & NaN & Brihat Samhita; BPHS; Surya Siddhanta; Jataka ... &
Sun & Moon & sextile & 60.0 & ... & NaN & NaN & NaN & NaN & NaN & NaN &
NaN & NaN & NaN & NaN \\
7 & aspects:000008 & aspects & Aspect sextile between Sun and Moon &
angle=60±8° & NaN & Brihat Samhita; BPHS; Surya Siddhanta; Jataka ... &
Sun & Moon & sextile & 60.0 & ... & NaN & NaN & NaN & NaN & NaN & NaN &
NaN & NaN & NaN & NaN \\
8 & aspects:000009 & aspects & Aspect square between Sun and Moon &
angle=90±1° & NaN & Brihat Samhita; BPHS; Surya Siddhanta; Jataka ... &
Sun & Moon & square & 90.0 & ... & NaN & NaN & NaN & NaN & NaN & NaN &
NaN & NaN & NaN & NaN \\
9 & aspects:000010 & aspects & Aspect square between Sun and Moon &
angle=90±3° & NaN & Brihat Samhita; BPHS; Surya Siddhanta; Jataka ... &
Sun & Moon & square & 90.0 & ... & NaN & NaN & NaN & NaN & NaN & NaN &
NaN & NaN & NaN & NaN \\
10 & aspects:000011 & aspects & Aspect square between Sun and Moon &
angle=90±5° & NaN & Brihat Samhita; BPHS; Surya Siddhanta; Jataka ... &
Sun & Moon & square & 90.0 & ... & NaN & NaN & NaN & NaN & NaN & NaN &
NaN & NaN & NaN & NaN \\
11 & aspects:000012 & aspects & Aspect square between Sun and Moon &
angle=90±8° & NaN & Brihat Samhita; BPHS; Surya Siddhanta; Jataka ... &
Sun & Moon & square & 90.0 & ... & NaN & NaN & NaN & NaN & NaN & NaN &
NaN & NaN & NaN & NaN \\
12 & aspects:000013 & aspects & Aspect trine between Sun and Moon &
angle=120±1° & NaN & Brihat Samhita; BPHS; Surya Siddhanta; Jataka ... &
Sun & Moon & trine & 120.0 & ... & NaN & NaN & NaN & NaN & NaN & NaN &
NaN & NaN & NaN & NaN \\
13 & aspects:000014 & aspects & Aspect trine between Sun and Moon &
angle=120±3° & NaN & Brihat Samhita; BPHS; Surya Siddhanta; Jataka ... &
Sun & Moon & trine & 120.0 & ... & NaN & NaN & NaN & NaN & NaN & NaN &
NaN & NaN & NaN & NaN \\
14 & aspects:000015 & aspects & Aspect trine between Sun and Moon &
angle=120±5° & NaN & Brihat Samhita; BPHS; Surya Siddhanta; Jataka ... &
Sun & Moon & trine & 120.0 & ... & NaN & NaN & NaN & NaN & NaN & NaN &
NaN & NaN & NaN & NaN \\
15 & aspects:000016 & aspects & Aspect trine between Sun and Moon &
angle=120±8° & NaN & Brihat Samhita; BPHS; Surya Siddhanta; Jataka ... &
Sun & Moon & trine & 120.0 & ... & NaN & NaN & NaN & NaN & NaN & NaN &
NaN & NaN & NaN & NaN \\
16 & aspects:000017 & aspects & Aspect opposition between Sun and Moon &
angle=180±1° & NaN & Brihat Samhita; BPHS; Surya Siddhanta; Jataka ... &
Sun & Moon & opposition & 180.0 & ... & NaN & NaN & NaN & NaN & NaN &
NaN & NaN & NaN & NaN & NaN \\
17 & aspects:000018 & aspects & Aspect opposition between Sun and Moon &
angle=180±3° & NaN & Brihat Samhita; BPHS; Surya Siddhanta; Jataka ... &
Sun & Moon & opposition & 180.0 & ... & NaN & NaN & NaN & NaN & NaN &
NaN & NaN & NaN & NaN & NaN \\
18 & aspects:000019 & aspects & Aspect opposition between Sun and Moon &
angle=180±5° & NaN & Brihat Samhita; BPHS; Surya Siddhanta; Jataka ... &
Sun & Moon & opposition & 180.0 & ... & NaN & NaN & NaN & NaN & NaN &
NaN & NaN & NaN & NaN & NaN \\
19 & aspects:000020 & aspects & Aspect opposition between Sun and Moon &
angle=180±8° & NaN & Brihat Samhita; BPHS; Surya Siddhanta; Jataka ... &
Sun & Moon & opposition & 180.0 & ... & NaN & NaN & NaN & NaN & NaN &
NaN & NaN & NaN & NaN & NaN \\
\end{longtable}

\phantomsection\label{combo-counts}
\begin{longtable}[]{@{}lll@{}}
\caption{Combination Counts by Category}\tabularnewline
\toprule\noalign{}
& category & count \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
& category & count \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & aspects & 720 \\
11 & malefic\_aspects & 120 \\
17 & sign & 108 \\
5 & house & 108 \\
9 & india\_nepal\_dasha\_pair & 81 \\
8 & india\_nepal\_antardasha\_pair & 81 \\
4 & graha\_yuddha & 36 \\
19 & tithi & 30 \\
16 & shadbala & 27 \\
20 & yoga & 27 \\
10 & karana & 11 \\
1 & combustion & 9 \\
7 & india\_dasha & 9 \\
12 & nakshatra & 9 \\
13 & nepal\_antardasha & 9 \\
14 & nepal\_dasha & 9 \\
15 & retrograde & 9 \\
6 & india\_antardasha & 9 \\
2 & compound & 6 \\
3 & eclipse & 2 \\
18 & syzygy & 2 \\
\end{longtable}

The full catalog is stored at
\texttt{docs/research/track\_2\_earthquake\_prediction/data/combination\_catalog.csv}.

\section{Algorithms and Worked
Examples}\label{algorithms-and-worked-examples}

This section formalizes each rule class into a concrete algorithmic
procedure.

\subsection{Algorithm A: Daily Astro Feature
Generation}\label{algorithm-a-daily-astro-feature-generation}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Compute planetary longitudes at local noon for each day.
\item
  Derive retrograde and combustion status.
\item
  Compute Panchanga elements (tithi, karana, yoga).
\item
  Compute houses using ascendant at the same timestamp.
\item
  Store a daily feature table for downstream combination evaluation.
\end{enumerate}

Implementation lives in
\texttt{docs/research/track\_2\_earthquake\_prediction/scripts/generate\_daily\_astro\_features.py}.

\subsection{Algorithm B: Combination
Evaluation}\label{algorithm-b-combination-evaluation}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Load the daily feature table.
\item
  For each combination in the catalog, evaluate its rule across all
  days.
\item
  Compute activation frequency and overlap with earthquake event
  windows.
\item
  Store results for graphing and significance testing.
\end{enumerate}

\subsection{Example: Aspect Rule (Mars--Saturn
square)}\label{example-aspect-rule-marssaturn-square}

Let \(\Delta = |\lambda_{Mars} - \lambda_{Saturn}| \bmod 360\).

Rule triggers if:

\[
|\Delta - 90^\circ| \leq 5^\circ
\]

\subsection{Example: Graha Yuddha}\label{example-graha-yuddha}

For any planet pair \((i,j)\):

\[
|\lambda_i - \lambda_j| < 1^\circ
\]

\subsection{Example: Combustion}\label{example-combustion}

For planet \(p\):

\[
|\lambda_p - \lambda_{Sun}| < 8^\circ
\]

\subsection{Example: Tithi}\label{example-tithi}

\[
Tithi = \left\lfloor \frac{(\lambda_{Moon}-\lambda_{Sun}) \bmod 360}{12} \right\rfloor + 1
\]

\section{Results: Hypothesis Testing (Combination
Frequencies)}\label{results-hypothesis-testing-combination-frequencies}

\subsection{13.1 Observed vs.~Expected
Frequencies}\label{observed-vs.-expected-frequencies}

To test the hypothesis that specific planetary combinations occur more
frequently during seismic windows, we calculated the \textbf{Activation
Frequency} for every combination in our catalog.

\begin{figure}[H]

\caption{\label{fig-category-activation}Activation Days by Combination
Category}

\centering{

\includegraphics{EARTHQUAKE_PREDICTION_INDIA_NEPAL_ANALYSIS_files/figure-pdf/fig-category-activation-output-1.png}

}

\end{figure}%

\begin{figure}[H]

\caption{\label{fig-top-activation}Top 25 Most Frequent Combinations}

\centering{

\includegraphics{EARTHQUAKE_PREDICTION_INDIA_NEPAL_ANALYSIS_files/figure-pdf/fig-top-activation-output-1.png}

}

\end{figure}%

\section{Alignment Windows vs
Earthquakes}\label{alignment-windows-vs-earthquakes}

This section compares \textbf{combination activation} against earthquake
windows (same day and ±N days).

\begin{figure}[H]

\caption{\label{fig-window-overlap}Average Overlap Rate by Category (±3
days)}

\centering{

\includegraphics{EARTHQUAKE_PREDICTION_INDIA_NEPAL_ANALYSIS_files/figure-pdf/fig-window-overlap-output-1.png}

}

\end{figure}%

\begin{figure}[H]

\caption{\label{fig-earthquake-zscores}Z-score Distribution vs Random
Baseline (±3 days)}

\centering{

\includegraphics{EARTHQUAKE_PREDICTION_INDIA_NEPAL_ANALYSIS_files/figure-pdf/fig-earthquake-zscores-output-1.png}

}

\end{figure}%

\begin{figure}[H]

\caption{\label{fig-window-compare}Overlap Rates by Window Size (All
Combinations)}

\centering{

\includegraphics{EARTHQUAKE_PREDICTION_INDIA_NEPAL_ANALYSIS_files/figure-pdf/fig-window-compare-output-1.png}

}

\end{figure}%

\begin{figure}[H]

\caption{\label{fig-top-overlap}Top 25 Combinations by ±3 Day Overlap}

\centering{

\includegraphics{EARTHQUAKE_PREDICTION_INDIA_NEPAL_ANALYSIS_files/figure-pdf/fig-top-overlap-output-1.png}

}

\end{figure}%

\subsection{Discussion and Synthesis}\label{discussion-and-synthesis}

\subsection{15.1 Null Hypothesis
Interpretation}\label{null-hypothesis-interpretation}

This study was designed to falsify the hypothesis that specific
planetary configurations act as precursors to major seismic events. -
\textbf{Null Hypothesis (\(H_0\))}: The frequency of earthquakes during
specific planetary alignments is not significantly different from the
frequency expected by random chance. - \textbf{Alternative Hypothesis
(\(H_1\))}: Specific alignments show a statistically significant
deviation in earthquake frequency.

Our analysis of the FDR-adjusted p-values (Table
\textbf{?@tbl-earthquake-significance}) indicates that for the vast
majority of tested combinations, we \textbf{fail to reject the Null
Hypothesis}. The few correlations that appear significant in isolation
often vanish when corrected for multiple comparisons, suggesting they
are likely statistical artifacts rather than physical signals.

\subsection{15.2 Limitations}\label{limitations}

While this study represents one of the most exhaustive computational
investigations into this topic, several limitations persist:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Catalog Completeness}: The analysis is limited to the USGS
  NEIC catalog (M \textgreater{} 6.0) for the defined region. Smaller
  magnitude events or historical events prior to reliable
  instrumentation were excluded.
\item
  \textbf{Epistemic constraints}: We tested \emph{classical} Vedic
  constraints (e.g., specific aspects, Yogas). It remains theoretically
  possible that a non-classical, highly complex, or non-linear
  combination exists that was not covered by our ontology.
\item
  \textbf{Physical Mechanism}: This study is purely statistical; it does
  not model potential physical mechanisms like tidal stress changes,
  which are generally considered too weak to trigger faults by orders of
  magnitude.
\end{enumerate}

\subsection{15.3 Conclusion for Track 2}\label{conclusion-for-track-2}

The comprehensive screening of classical astrological configurations
against the India-Nepal earthquake record yields no robust evidence of
predictive utility. The severe testing framework reinforces the
consensus that earthquakes are stochastic processes with respect to
celestial mechanics.

\section{Appendix: Full Definitions and
Formulae}\label{appendix-full-definitions-and-formulae}

This appendix enumerates all formulae, thresholds, and default
parameters used in combination generation and evaluation.

\begin{itemize}
\tightlist
\item
  Orb sets: \{1°, 3°, 5°, 8°\}
\item
  Eclipse node proximity: 12°
\item
  Syzygy tithis: 15 (Full), 30 (New)
\item
  Window sizes: \{0, ±1, ±3, ±7, ±14, ±30 days\}
\end{itemize}

All generated tables:

\begin{itemize}
\tightlist
\item
  \texttt{docs/research/track\_2\_earthquake\_prediction/data/combination\_catalog.csv}
\item
  \texttt{docs/research/track\_2\_earthquake\_prediction/data/daily\_astro\_base.csv}
\item
  \texttt{docs/research/track\_2\_earthquake\_prediction/data/combination\_metrics.csv}
\end{itemize}

\section{Introduction}\label{introduction}

\subsection{The Earthquake Prediction
Challenge}\label{the-earthquake-prediction-challenge}

The prediction of earthquakes remains one of the most persistent
challenges in geophysical science. Despite decades of research, no
reliable deterministic earthquake prediction method exists. The
``Prediction Gap''---the inability to forecast the time, location, and
magnitude of rupture---stems from the non-linear, chaotic nature of
crustal stress accumulation.

\subsection{Astrological Claims}\label{astrological-claims}

Traditional astrology, particularly the school of \textbf{Mundane
Astrology} described in Varahamihira's Brihat Samhita (Varahamihira c.
6th century CE), has long claimed the ability to predict natural
disasters including earthquakes through planetary configurations.
Specific claims include:

\begin{itemize}
\tightlist
\item
  \textbf{Mars-Saturn Conjunctions}: Trigger catastrophic events
\item
  \textbf{Eclipses in Cardinal Signs}: Activate seismic stress
\item
  \textbf{Malefic Transits through 4th House}: Destabilize foundations
\end{itemize}

This study tests these claims using modern statistical methods on a
well-defined geographic region.

\subsection{Research Objectives}\label{research-objectives}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Define a quantitative ``Planetary Stress Index'' from Vedic principles
\item
  Collect and process USGS earthquake data for India-Nepal region
\item
  Apply regression analysis to test predictive relationships
\item
  Validate findings using Monte Carlo ``Look-Elsewhere'' analysis
\end{enumerate}

\subsection{Literature Review}\label{literature-review}

Classical Jyotish texts attribute natural phenomena to planetary
dynamics and cyclic time, providing the conceptual basis for modern
``mundane astrology'' claims (Parashara c. 7th century CE; Varahamihira
c. 6th century CE). These sources establish the principles of malefic
influence (Mars, Saturn, Rahu, Ketu), planetary strengths, and the role
of eclipses and transits in large-scale events (Parashara c. 7th century
CE; Anonymous c. 4th century CE).

Modern seismology, by contrast, emphasizes probabilistic hazard and
event clustering, where rigorous statistical baselines are essential to
avoid false discovery (Molchan 1997; Gardner and Knopoff 1974). The USGS
ComCat provides standardized, globally curated event data suitable for
reproducible testing of prediction claims (United States Geological
Survey 2024). Methodologically, multiple testing correction and Monte
Carlo validation are standard tools for distinguishing signal from noise
when exploring many candidate predictors (Bonferroni 1936; Fishman
1996).

This study bridges these domains by formalizing classical astrological
concepts into quantitative features and evaluating them using
contemporary statistical frameworks designed for overdispersed event
counts.

\section{Background: The India-Nepal Tectonic
Zone}\label{background-the-india-nepal-tectonic-zone}

\subsection{Geological Context}\label{geological-context}

The India-Nepal border sits atop one of Earth's most dramatic tectonic
features---the collision zone between the Indian Plate and the Eurasian
Plate. This ongoing collision, which began \textasciitilde50 million
years ago, creates the Himalayan mountain range and generates
significant seismic hazard.

\subsubsection{Key Geological Features}\label{key-geological-features}

\begin{longtable}[]{@{}ll@{}}
\caption{India-Nepal Tectonic
Features}\label{tbl-geology}\tabularnewline
\toprule\noalign{}
Feature & Description \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Feature & Description \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Plate Boundary & Indian Plate subducting beneath Eurasian Plate \\
Collision Rate & \textasciitilde45-50 mm/year \\
Major Fault & Main Himalayan Thrust (MHT) \\
Seismic Gap & Central Nepal (locked since 1505 CE) \\
\end{longtable}

\subsection{Historical Seismicity}\label{historical-seismicity}

The region has experienced devastating earthquakes:

\begin{itemize}
\tightlist
\item
  \textbf{1934 Bihar-Nepal Earthquake}: M8.0, \textasciitilde10,700
  deaths
\item
  \textbf{2015 Gorkha Earthquake}: M7.8, \textasciitilde9,000 deaths
\item
  \textbf{2023 West Nepal Earthquake}: M5.6, 150+ deaths
\end{itemize}

The persistence of seismic hazard makes this an important test case for
any prediction system.

\section{Astrological Principles and Pattern
Hypotheses}\label{astrological-principles-and-pattern-hypotheses}

This study operationalizes a core subset of classical Vedic principles
commonly cited in disaster-oriented astrology (Mundane Jyotish). The
intent is not to endorse the claims, but to formalize them into testable
variables (Parashara c. 7th century CE; Varahamihira c. 6th century CE).

\subsection{Malefic Planets and
Stress}\label{malefic-planets-and-stress}

The malefic planets \textbf{Mars (Mangal)} and \textbf{Saturn (Shani)}
are traditionally associated with rupture, conflict, and structural
breakdown. Their close angular relationships and combined weakness are
hypothesized to correlate with geophysical instability (Parashara c. 7th
century CE).

\subsection{Shadbala Components (Sixfold
Strength)}\label{shadbala-components-sixfold-strength-1}

Shadbala is decomposed into six classical components, each representing
a distinct dimension of planetary strength (Parashara c. 7th century
CE):

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Sthāna Bala} (positional strength)
\item
  \textbf{Dig Bala} (directional strength)
\item
  \textbf{Kāla Bala} (temporal strength)
\item
  \textbf{Chesta Bala} (motional strength, including retrograde)
\item
  \textbf{Naisargika Bala} (natural/inherent strength)
\item
  \textbf{Drik Bala} (aspectual strength)
\end{enumerate}

These are aggregated to estimate whether the sky is in a ``stable'' or
``unstable'' state.

\subsection{Graha Yuddha (Planetary
War)}\label{graha-yuddha-planetary-war}

When two planets are within \textasciitilde1° longitude, classical texts
describe a conflict where the weaker planet is overpowered, potentially
signaling abrupt shifts in terrestrial conditions (Parashara c. 7th
century CE). We encode this as a discrete indicator of close planetary
conjunctions.

\subsection{Malefic Aspects and
Angularity}\label{malefic-aspects-and-angularity}

Hard aspects (especially \textbf{90°} and \textbf{180°} between Mars and
Saturn) are treated as destabilizing configurations. In mundane
interpretation, such relationships indicate stress accumulation that may
manifest on Earth (Varahamihira c. 6th century CE).

\subsection{Eclipses, Lunar Phases, and Temporal
Windows}\label{eclipses-lunar-phases-and-temporal-windows}

Eclipses and syzygy (new/full moon alignment) are frequently highlighted
in classical texts and modern astrology as temporally sensitive
``activation windows'' (Anonymous c. 4th century CE; Varahamihira c. 6th
century CE). In this analysis, eclipse windows are treated as
categorical temporal markers for stress clustering.

\section{Data and Methodology}\label{data-and-methodology}

\subsection{Phase 1: Earthquake Data
Collection}\label{phase-1-earthquake-data-collection}

\subsubsection{Data Source}\label{data-source}

We utilized the \textbf{USGS Earthquake Hazards Program} Comprehensive
Earthquake Catalog (ComCat), accessed via the official API (United
States Geological Survey 2024).

\subsubsection{Filter Criteria}\label{filter-criteria}

\begin{longtable}[]{@{}ll@{}}
\caption{Data Collection Parameters}\label{tbl-params}\tabularnewline
\toprule\noalign{}
Parameter & Value \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Parameter & Value \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Latitude Range} & 20°N to 35°N \\
\textbf{Longitude Range} & 75°E to 90°E \\
\textbf{Time Period} & January 1, 2015 to January 1, 2024 \\
\textbf{Magnitude Threshold} & M ≥ 4.5 \\
\textbf{Catalog} & USGS/NEIC \\
\end{longtable}

\subsubsection{Dataset Summary}\label{dataset-summary}

After filtering and quality control:

\begin{longtable}[]{@{}ll@{}}
\caption{Dataset Summary}\label{tbl-dataset}\tabularnewline
\toprule\noalign{}
Statistic & Value \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Statistic & Value \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Total Events & 370 \\
Magnitude Range & 4.5 to 7.8 \\
Depth Range & 5 km to 100 km \\
Peak Year & 2015 (Nepal earthquake sequence) \\
\end{longtable}

\subsubsection{Exploratory Data Visuals}\label{exploratory-data-visuals}

The following figures establish baseline seismic characteristics in the
study region.

\begin{figure}[H]

\caption{\label{fig-seismic-timeline}Earthquake Timeline (2015-2024)}

\centering{

\includegraphics{EARTHQUAKE_PREDICTION_INDIA_NEPAL_ANALYSIS_files/figure-pdf/fig-seismic-timeline-output-1.png}

}

\end{figure}%

\begin{figure}[H]

\caption{\label{fig-magnitude-hist}Magnitude Distribution (M ≥ 4.5)}

\centering{

\includegraphics{EARTHQUAKE_PREDICTION_INDIA_NEPAL_ANALYSIS_files/figure-pdf/fig-magnitude-hist-output-1.png}

}

\end{figure}%

\begin{figure}[H]

\caption{\label{fig-depth-hist}Depth Distribution}

\centering{

\includegraphics{EARTHQUAKE_PREDICTION_INDIA_NEPAL_ANALYSIS_files/figure-pdf/fig-depth-hist-output-1.png}

}

\end{figure}%

\begin{figure}[H]

\caption{\label{fig-spatial}Spatial Distribution of Events}

\centering{

\includegraphics{EARTHQUAKE_PREDICTION_INDIA_NEPAL_ANALYSIS_files/figure-pdf/fig-spatial-output-1.png}

}

\end{figure}%

\begin{figure}[H]

\caption{\label{fig-gutenberg}Gutenberg-Richter Style Curve
(Cumulative)}

\centering{

\includegraphics{EARTHQUAKE_PREDICTION_INDIA_NEPAL_ANALYSIS_files/figure-pdf/fig-gutenberg-output-1.png}

}

\end{figure}%

\FloatBarrier

\subsubsection{Overdispersion Check
(Counts)}\label{overdispersion-check-counts}

We aggregate events to daily counts and compare variance vs mean.
Overdispersion motivates Negative Binomial modeling (Gardner and Knopoff
1974).

\begin{longtable}[]{@{}llllll@{}}

\caption{\label{tbl-overdispersion}Daily Count Overdispersion Summary}

\tabularnewline

\toprule\noalign{}
& Days & Mean Count & Variance & Variance/Mean & Zero-Event Days \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & 256 & 1.445312 & 9.910723 & 6.857149 & 0 \\

\end{longtable}

\begin{figure}[H]

\caption{\label{fig-counts}Daily Earthquake Counts (Distribution)}

\centering{

\includegraphics{EARTHQUAKE_PREDICTION_INDIA_NEPAL_ANALYSIS_files/figure-pdf/fig-counts-output-1.png}

}

\end{figure}%

\FloatBarrier

\subsection{Phase 2: Astrological Feature
Engineering}\label{phase-2-astrological-feature-engineering}

\subsubsection{The Planetary Stress
Index}\label{the-planetary-stress-index}

We developed a quantitative ``Astro-Fusion Stress Index'' based on three
classical Vedic principles:

\paragraph{1. Aggregate Shadbala (Planetary
Weakness)}\label{aggregate-shadbala-planetary-weakness}

Low combined Shadbala scores indicate planetary ``instability'':

\[
Stress_{Shadbala} = 100 - \frac{1}{n}\sum_{p}^{planets} \sigma_p
\]

\paragraph{2. Graha Yuddha (Planetary
Wars)}\label{graha-yuddha-planetary-wars}

Conjunctions within 1° longitude create tension:

\[
Stress_{Yuddha} = \sum_{i,j} \mathbb{1}[|\lambda_i - \lambda_j| < 1°]
\]

\paragraph{3. Malefic Aspects}\label{malefic-aspects}

Saturn-Mars squares (90°) and oppositions (180°):

\[
Stress_{Aspect} = \mathbb{1}[|(\lambda_{Saturn} - \lambda_{Mars})| \in \{90° \pm 5°, 180° \pm 5°\}]
\]

\subsubsection{Combined Index}\label{combined-index}

\[
Stress_{Total} = w_1 \cdot Stress_{Shadbala} + w_2 \cdot Stress_{Yuddha} + w_3 \cdot Stress_{Aspect}
\]

\subsubsection{Methodology Pipeline
(End-to-End)}\label{methodology-pipeline-end-to-end}

\begin{itemize}
\tightlist
\item
  \textbf{USGS Events (2015-2024)} -\textgreater{} Filter by region \&
  magnitude -\textgreater{} Daily event counts
\item
  \textbf{Planetary positions (Swiss Ephemeris)} -\textgreater{} Astro
  feature extraction -\textgreater{} Planetary Stress Index
\item
  \textbf{Model} -\textgreater{} Negative Binomial GLM (using Daily
  event counts and Planetary Stress Index)
\item
  \textbf{Validation} -\textgreater{} Coefficient tests + AIC
  -\textgreater{} Monte Carlo permutation -\textgreater{} Empirical
  p-values
\end{itemize}

\textbf{Algorithm 1: Seismo-Astro Validation Pipeline}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Collect} USGS event data for India-Nepal and compute daily
  counts.
\item
  \textbf{Compute} daily planetary variables using Swiss Ephemeris.
\item
  \textbf{Construct} the Planetary Stress Index from Shadbala, Graha
  Yuddha, and malefic aspects.
\item
  \textbf{Model} daily event counts with Negative Binomial regression.
\item
  \textbf{Validate} via Monte Carlo permutations of astrological
  features.
\end{enumerate}

\subsection{Phase 3: Statistical
Framework}\label{phase-3-statistical-framework}

\subsubsection{Negative Binomial
Regression}\label{negative-binomial-regression}

Earthquake counts exhibit \textbf{overdispersion} (\(Variance > Mean\))
due to clustering. Standard Poisson regression is inappropriate. We
employ a Negative Binomial Generalized Linear Model (GLM):

\[
\ln(\mu_t) = \beta_0 + \beta_{trend}t + \beta_{season}\sin(\frac{2\pi t}{365}) + \beta_{astro}X_{astro}
\]

\subsubsection{The Null Hypothesis}\label{the-null-hypothesis}

\[
H_0: \text{Planetary variables provide no information gain over baseline model}
\]

The baseline model includes only: - Long-term catalog improvement trend
- Annual seasonal cycle (tidal effects) - Random Poisson noise

\subsubsection{Monte Carlo ``Look-Elsewhere''
Analysis}\label{monte-carlo-look-elsewhere-analysis}

To guard against false discoveries from testing multiple variables:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Destroy temporal alignment (shuffle planetary data)
\item
  Preserve internal autocorrelation structure
\item
  Compute Delta-AIC for 1,000 permutations
\item
  Build empirical null distribution
\item
  Calculate p-value as fraction exceeding observed value
\end{enumerate}

\section{Results}\label{results}

\subsection{Seismic Activity Timeline}\label{seismic-activity-timeline}

The dataset reveals distinct patterns:

\begin{itemize}
\tightlist
\item
  \textbf{2015}: Massive clustering due to Gorkha earthquake sequence
\item
  \textbf{2016-2022}: Sporadic moderate activity
\item
  \textbf{2023}: Renewed activity in western Nepal
\end{itemize}

The non-uniform distribution confirms the need for
overdispersion-corrected models.

\begin{figure}[H]

\caption{\label{fig-phase1}}

\centering{

\captionsetup{labelsep=none}\includegraphics[width=0.9\textwidth,height=\textheight]{figures/phase1_seismic_timeline.png}

}

\end{figure}%

\subsection{Regression Analysis
Results}\label{regression-analysis-results}

\subsubsection{Model Coefficients}\label{model-coefficients}

\begin{longtable}[]{@{}lllll@{}}
\caption{Regression Coefficients}\label{tbl-regression}\tabularnewline
\toprule\noalign{}
Variable & Coefficient & Std. Error & p-value & Significant? \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Variable & Coefficient & Std. Error & p-value & Significant? \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Intercept & -0.900 & 0.388 & 0.02 & Yes \\
Year Index & 0.011 & 0.062 & 0.86 & No \\
Universal Day 8 (Saturn) & 0.143 & 0.213 & 0.50 & No \\
Mars Strength & -0.005 & 0.003 & 0.10 & No \\
Saturn Strength & 0.000 & 0.003 & 0.99 & No \\
\end{longtable}

\subsubsection{Interpretation}\label{interpretation}

\begin{itemize}
\tightlist
\item
  \textbf{Mars Strength}: Shows weak negative correlation
  (\(p = 0.10\))---marginally suggestive but fails significance
  threshold
\item
  \textbf{Saturn Strength}: No relationship whatsoever (\(p = 0.99\))
\item
  \textbf{Universal Day 8}: No numerological signal (\(p = 0.50\))
\item
  \textbf{Year Index}: No significant trend in seismic rate
\end{itemize}

\subsection{Monte Carlo Validation}\label{monte-carlo-validation}

The ``Look-Elsewhere'' analysis tested whether observed results could
arise by chance:

\begin{longtable}[]{@{}ll@{}}
\caption{Monte Carlo Results}\label{tbl-montecarlo}\tabularnewline
\toprule\noalign{}
Metric & Value \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Metric & Value \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Real Signal Delta-AIC & 22.13 \\
95th Percentile Noise Floor & 27.95 \\
99th Percentile Noise Floor & 35.21 \\
Empirical p-value & 0.38 \\
\end{longtable}

\textbf{Result}: The real data signal (22.13) falls \textbf{below} the
95th percentile of random noise (27.95), indicating the observed
``signal'' is indistinguishable from chance.

\begin{figure}[H]

\caption{\label{fig-montecarlo}}

\centering{

\captionsetup{labelsep=none}\includegraphics[width=0.9\textwidth,height=\textheight]{figures/monte_carlo_distribution.png}

}

\end{figure}%

\subsection{Pattern Mapping
Visualization}\label{pattern-mapping-visualization}

Overlaying the Planetary Stress Index with actual earthquake occurrences
reveals:

\begin{itemize}
\tightlist
\item
  No consistent alignment between ``High Stress'' periods and major
  earthquakes
\item
  The 2015 Gorkha sequence occurred during a moderate (not extreme)
  stress period
\item
  Several ``High Stress'' periods passed without significant seismicity
\end{itemize}

\begin{figure}[H]

\caption{\label{fig-phase2}}

\centering{

\captionsetup{labelsep=none}\includegraphics[width=0.9\textwidth,height=\textheight]{figures/phase2_astro_pattern_map.png}

}

\end{figure}%

\subsection{Scatter Plot Analysis}\label{scatter-plot-analysis}

Plotting Earthquake Magnitude against Planetary Stress Index:

\begin{longtable}[]{@{}ll@{}}
\caption{Scatter Analysis}\label{tbl-scatter}\tabularnewline
\toprule\noalign{}
Expected (if predictive) & Observed \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Expected (if predictive) & Observed \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Diagonal clustering & Random scatter \\
High Mag → High Stress & Uniform distribution \\
\end{longtable}

Large magnitude events occur at both high and low stress levels with
equal probability.

\begin{figure}[H]

\caption{\label{fig-phase3}}

\centering{

\captionsetup{labelsep=none}\includegraphics[width=0.9\textwidth,height=\textheight]{figures/phase3_validation_scatter.png}

}

\end{figure}%

\FloatBarrier

\section{Discussion}\label{discussion}

\subsection{Failure to Reject Null
Hypothesis}\label{failure-to-reject-null-hypothesis}

Based on three independent lines of evidence, we \textbf{fail to reject
the null hypothesis}:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Regression p-values}: All planetary variables \textgreater{}
  0.05
\item
  \textbf{Monte Carlo validation}: Signal within noise distribution
\item
  \textbf{Visual inspection}: No consistent pattern matching
\end{enumerate}

\subsection{Potential Confounders}\label{potential-confounders}

\subsubsection{Solar Cycle}\label{solar-cycle}

The 11-year solar maximum cycle may overlap with certain planetary
periods (particularly Jupiter's 12-year orbit). Future studies should
include solar activity as a covariate.

\subsubsection{Tidal Stress}\label{tidal-stress}

Lunar phases (syzygy) are \textbf{known physical triggers} for
earthquake initiation. However, these represent actual gravitational
effects, not ``astrological'' influences. Our analysis separated these
mechanisms.

\subsubsection{Regional vs.~Global}\label{regional-vs.-global}

This study focused on a single tectonic region. Different results might
emerge for: - Subduction zones (Pacific Ring of Fire) - Transform
boundaries (San Andreas) - Intraplate earthquakes (New Madrid)

\subsection{The Near-Threshold Mars
Signal}\label{the-near-threshold-mars-signal}

The Mars coefficient (\(p = 0.10\)) warrants comment. While not
statistically significant:

\begin{itemize}
\tightlist
\item
  Could represent Type II error with small sample
\item
  May indicate weak but real tidal influence (Mars affects Earth's
  tides, though minimally)
\item
  More likely: random fluctuation near threshold
\end{itemize}

Future research with larger datasets (\textgreater10,000 events) could
resolve this ambiguity.

\subsection{Methodological Strengths}\label{methodological-strengths}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Precise Geographic Focus}: Well-defined tectonic region with
  known characteristics
\item
  \textbf{Proper Statistical Framework}: Negative Binomial for
  overdispersion
\item
  \textbf{Multiple Testing Control}: Bonferroni and Monte Carlo methods
\item
  \textbf{Reproducible Pipeline}: Open-source code and data
\end{enumerate}

\subsection{Model Diagnostics and
Robustness}\label{model-diagnostics-and-robustness}

We emphasize model stability and robustness across assumptions:

\begin{itemize}
\tightlist
\item
  \textbf{Overdispersion}: Daily counts exhibit variance substantially
  exceeding the mean, validating Negative Binomial modeling.
\item
  \textbf{Permutation Checks}: Monte Carlo shuffling preserves temporal
  structure while destroying astro alignment, guarding against spurious
  correlations (Fishman 1996).
\item
  \textbf{Multiple Testing Control}: Reported signals are interpreted in
  the context of multiple hypothesis evaluation (Bonferroni 1936).
\end{itemize}

\subsection{Limitations}\label{limitations-1}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Sample Size}: 370 events may be insufficient for detecting
  weak signals
\item
  \textbf{Temporal Scope}: 9 years may miss long-period planetary cycles
\item
  \textbf{Linear Assumptions}: Non-linear relationships not explored
\item
  \textbf{Technique Coverage}: Many Jyotish techniques untested (Koorma
  Chakra, Ashtakavarga)
\end{enumerate}

\subsection{Ethical and Practical
Considerations}\label{ethical-and-practical-considerations}

Earthquake prediction has direct public safety implications. Any method
that does not demonstrate robust statistical validity should not be used
for emergency planning, public warnings, or risk communication. This
study is explicitly \textbf{diagnostic}, not prescriptive, and
emphasizes reproducible evaluation rather than operational prediction.

\subsection{Reproducibility and Data
Availability}\label{reproducibility-and-data-availability}

\begin{itemize}
\tightlist
\item
  \textbf{Data}: USGS ComCat API and the curated India-Nepal dataset in
  this repository.
\item
  \textbf{Code}: Feature extraction and statistical modeling scripts in
  the research pipeline.
\item
  \textbf{Determinism}: Given the same date range and location
  constraints, results should be reproducible.
\end{itemize}

\section{Conclusions}\label{conclusions}

This rigorous investigation of earthquake prediction using Vedic
Astrology yields definitive results:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{No Significant Predictors}: All tested planetary variables
  failed statistical significance
\item
  \textbf{Monte Carlo Confirmation}: Observed ``signals'' fall within
  random noise distribution
\item
  \textbf{Null Hypothesis Maintained}: Planetary configurations do not
  predict earthquakes in this dataset
\item
  \textbf{Mars Marginal Effect}: Weak signal warrants further
  investigation with larger samples
\item
  \textbf{Saturn Non-Effect}: Complete absence of relationship
  (\(p = 0.99\))
\end{enumerate}

\subsection{Implications}\label{implications}

For practitioners and researchers:

\begin{itemize}
\tightlist
\item
  \textbf{Astrological prediction of specific earthquake timing is not
  supported} by this analysis
\item
  Planetary configurations may have value for other purposes but not
  seismic forecasting
\item
  \textbf{Standard seismological methods} remain the appropriate
  approach for hazard assessment
\end{itemize}

\subsection{Future Research
Directions}\label{future-research-directions}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Extended Dataset}: Analysis with USGS global catalog
  (\textgreater100,000 events)
\item
  \textbf{Koorma Chakra Testing}: Regional zodiac mapping as per
  classical texts
\item
  \textbf{Machine Learning}: Non-linear approaches (Random Forests,
  Neural Networks)
\item
  \textbf{Multi-Region Comparison}: Testing across different tectonic
  environments
\end{enumerate}

\section{References}\label{references}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-surya_siddhanta}
Anonymous. c. 4th century CE. \emph{Surya Siddhanta: A Textbook of Hindu
Astronomy}. Various translations.

\bibitem[\citeproctext]{ref-bonferroni_correction}
Bonferroni, Carlo Emilio. 1936. {``Teoria Statistica Delle Classi e
Calcolo Delle Probabilità.''} \emph{Pubblicazioni Del R Istituto
Superiore Di Scienze Economiche e Commerciali Di Firenze} 8: 3--62.

\bibitem[\citeproctext]{ref-jataka_parijata}
Dikshita, Vaidyanatha. c. 14th century CE. \emph{Jataka Parijata}.

\bibitem[\citeproctext]{ref-monte_carlo_methods}
Fishman, George S. 1996. \emph{Monte Carlo: Concepts, Algorithms, and
Applications}. Springer.

\bibitem[\citeproctext]{ref-gardner_knopoff}
Gardner, J. K., and L. Knopoff. 1974. {``Is the Sequence of Earthquakes
in Southern California, with Aftershocks Removed, Poissonian?''}
\emph{Bulletin of the Seismological Society of America} 64 (5):
1363--67.

\bibitem[\citeproctext]{ref-molchan_diagram}
Molchan, G. M. 1997. {``Earthquake Prediction as a Decision-Making
Problem.''} \emph{Pure and Applied Geophysics} 149: 233--47.
\url{https://doi.org/10.1007/BF00945169}.

\bibitem[\citeproctext]{ref-bphs}
Parashara, Sage. c. 7th century CE. \emph{Brihat Parashara Hora
Shastra}. Various translations.

\bibitem[\citeproctext]{ref-usgs_earthquake}
United States Geological Survey. 2024. {``USGS Earthquake Hazards
Program: Comprehensive Earthquake Catalog.''}
\url{https://earthquake.usgs.gov/earthquakes/search/}.

\bibitem[\citeproctext]{ref-varahamihira_brihat_samhita}
Varahamihira. c. 6th century CE. \emph{Brihat Samhita}.

\bibitem[\citeproctext]{ref-saravali}
Varma, Kalyana. c. 8th century CE. \emph{Saravali}.

\end{CSLReferences}

\section{Appendix A: Data Processing
Pipeline}\label{appendix-a-data-processing-pipeline}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# USGS API Query}
\ImportTok{import}\NormalTok{ requests}

\NormalTok{url }\OperatorTok{=} \StringTok{"https://earthquake.usgs.gov/fdsnws/event/1/query"}
\NormalTok{params }\OperatorTok{=}\NormalTok{ \{}
    \StringTok{"format"}\NormalTok{: }\StringTok{"geojson"}\NormalTok{,}
    \StringTok{"starttime"}\NormalTok{: }\StringTok{"2015{-}01{-}01"}\NormalTok{,}
    \StringTok{"endtime"}\NormalTok{: }\StringTok{"2024{-}01{-}01"}\NormalTok{,}
    \StringTok{"minlatitude"}\NormalTok{: }\DecValTok{20}\NormalTok{,}
    \StringTok{"maxlatitude"}\NormalTok{: }\DecValTok{35}\NormalTok{,}
    \StringTok{"minlongitude"}\NormalTok{: }\DecValTok{75}\NormalTok{,}
    \StringTok{"maxlongitude"}\NormalTok{: }\DecValTok{90}\NormalTok{,}
    \StringTok{"minmagnitude"}\NormalTok{: }\FloatTok{4.5}
\NormalTok{\}}
\NormalTok{response }\OperatorTok{=}\NormalTok{ requests.get(url, params}\OperatorTok{=}\NormalTok{params)}
\NormalTok{earthquakes }\OperatorTok{=}\NormalTok{ response.json()[}\StringTok{"features"}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\section{Appendix B: Negative Binomial Model
Specification}\label{appendix-b-negative-binomial-model-specification}

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{import}\NormalTok{ statsmodels.api }\ImportTok{as}\NormalTok{ sm}

\CommentTok{\# Model specification}
\NormalTok{model }\OperatorTok{=}\NormalTok{ sm.GLM(}
\NormalTok{    earthquake\_counts,}
\NormalTok{    features,}
\NormalTok{    family}\OperatorTok{=}\NormalTok{sm.families.NegativeBinomial()}
\NormalTok{)}
\NormalTok{results }\OperatorTok{=}\NormalTok{ model.fit()}
\end{Highlighting}
\end{Shaded}

\section{Appendix C: Data
Availability}\label{appendix-c-data-availability}

All earthquake data, planetary calculations, and analysis code are
available at:
https://github.com/astro-fusion/astro\_research-white-paper/tree/main/docs/research/track\_2\_earthquake\_prediction



\end{document}
