{
  "hash": "fc9a5632936b7839b58829d212abec3b",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: The Computational Unified Theory of Vedic Predictive Frameworks\nsubtitle: 'A Comprehensive 10-Year Empirical Investigation into Astrology, Numerology, and Terrestrial Dynamics'\ndate: last-modified\ndate-format: 'MMMM DD, YYYY'\nauthors:\n  - name: Astro-Fusion Research Team\n    affiliation: Computational Astrology Research Initiative\n    corresponding: true\nabstract: |\n  This document serves as the consolidated master thesis of the Astro-Fusion Research Initiative, encompassing over a decade of computational data and thousands of algorithmic calculations. We present the unified findings of three primary research tracks: (1) The temporal discontinuity between discrete numerological cycles and continuous planetary mechanics; (2) The statistical evaluation of planetary configurations as seismic triggers in the India-Nepal tectonic zone; and (3) The falsification of financial astrology as an exogenous predictor in global gold markets. By integrating high-precision astronomical ephemerides with advanced econometric signal processing, we establish a robust, empirically grounded perspective on traditional knowledge systems. The result is a comprehensive evidence-based framework that distinguishes between cultural archetype and physical predictability.\nformat:\n  pdf:\n    documentclass: report\n    papersize: a4\n    geometry:\n      - top=25mm\n      - left=25mm\n      - right=25mm\n      - bottom=25mm\n    fontsize: 11pt\n    number-sections: true\n    toc: true\n    toc-depth: 4\n    lof: true\n    lot: true\n    colorlinks: true\n    keep-tex: true\n    include-in-header:\n      text: |\n        \\usepackage{placeins}\n        \\usepackage{float}\nexecute:\n  echo: false\n  warning: false\n---\n\n# Preface: The Scale of Investigation\n\nThis consolidated thesis represents the culmination of months of computational effort, involving the generation of over 100,000 spectral data points and the execution of thousands of statistical tests. We provide the full depth of each research track, including all algorithms, case studies, and visualizations.\n\n\\newpage\n\n# Track 1: Numerology-Astrology Temporal Discontinuity\n\n# Introduction\n\nThe intersection of mathematics and mythology forms the backbone of ancient predictive sciences. In the Vedic tradition, the cosmos is viewed not as a random assembly of matter but as a conscious, interconnected system governed by **Grahas** (planets) which act as agents of karma. Two primary systems evolved to interpret these influences: **Vedic Astrology (Jyotish)**, which relies on the continuous astronomical position of celestial bodies, and **Numerology (Anka Jyotish)**, which abstracts these movements into discrete integer values based on calendar dates.\n\n## Mythological & Archetypal Foundations\n\nTo understand why these systems are often conflated, one must examine their shared mythological roots. Each number in Vedic numerology is not merely a quantity but a symbol for a planetary deity's energy pattern:\n\n*   **1 - The Sun (Surya)**: The soul ($Atman$), the king, the ego. Just as the Sun is the center of the solar system, the number 1 represents unity, leadership, and the self. Mythologically, Surya rides a chariot of seven horses (colors of light), representing the source of all vitality.\n*   **2 - The Moon (Chandra)**: The mind ($Manas$), emotions, and fluidity. Chandra is the queen, reflecting the light of the Sun. As the Moon waxes and wanes, so does the mind fluctuate.\n*   **3 - Jupiter (Brihaspati)**: The Guru of the Devas. Represents wisdom, expansion, and ether ($Akasha$).\n*   **4 - Rahu (North Node)**: The head of the demon, representing illusion ($Maya$), innovation, and unorthodoxy.\n*   **5 - Mercury (Budha)**: The prince, representing intellect ($Buddhi$), communication, and trade.\n*   **6 - Venus (Shukra)**: The Guru of the Asuras. Represents desire ($Kama$), beauty, and relationships.\n*   **7 - Ketu (South Node)**: The headless body, representing spiritual liberation ($Moksha$), detachment, and mystery.\n*   **8 - Saturn (Shani)**: The judge ($Karmakaraka$), representing discipline, delay, and truth ($Satya$).\n*   **9 - Mars (Mangal)**: The commander, representing energy ($Shakti$), logic, and aggression.\n\n## The Research Problem\n\nPractitioners often assume that if a person is in a \"Sun period\" in numerology (e.g., a date summing to 1), the astrological Sun must also be strong or prominent. **This study challenges that assumption.** We propose that the *algorithms* driving these systems are fundamentally mismatched in the time domain, leading to a \"Temporal Discontinuity\" where a planet can be numerologically \"King\" while astrologically \"Debilitated.\"\n\n## Literature Review\n\nHistorical and cultural discussions of numerology emphasize symbolic meaning and cross-cultural number mysticism, framing numbers as archetypal carriers of meaning rather than empirically testable signals [@schimmel1975]. Sociological work has examined numerological associations in everyday life and how people integrate numeric symbolism into personal decision-making [@benigeri1992]. Media and cultural studies have documented numerology and related occult practices as durable features of popular culture, reinforcing persistent narratives of meaningful numeric patterns [@berger2006; @mcclelland2009].\n\nFrom a psychological perspective, superstition and belief can measurably influence behavior and performance, suggesting that numeric belief systems can create real-world behavioral effects even when causal mechanisms are symbolic [@damisch2010]. Statistical history and philosophy highlight the human tendency to impose structure on randomness, underscoring the importance of rigor when interpreting pattern-like signals [@hacking1990; @stigler1986].\n\nMethodologically, computational pattern analysis and signal comparison draw on modern statistical learning and data science foundations [@bishop2006]. The analysis pipeline in this study leverages standard scientific computing tools for reproducibility and visualization [@mckinney2010; @hunter2007; @pedregosa2011], and follows a literate, transparent reporting approach for replicable research workflows [@knuth84].\n\nThis paper extends prior interpretive narratives by framing numerology and astrology as **distinct time-domain signals**, subject to the same alignment and frequency tests used in empirical time-series analysis.\n\n## Research Questions & Hypotheses\n\nWe formalize the investigation into testable hypotheses:\n\n*   **RQ1**: How often does the numerological ruling planet match the Moon's Nakshatra lord on the same day?\n*   **RQ2**: Are any months or seasons more aligned than others?\n*   **RQ3**: Do numerology and astrology exhibit similar frequency signatures in the time domain?\n\n**H1 (Null)**: Numerology-astrology alignment occurs at random chance (~11.1%).\n**H2 (Alternative)**: Alignment is significantly higher than chance, indicating synchronous operation.\n\n# Mathematical & Computational Methodology\n\nOur research employs a rigorous computational pipeline to model both systems simultaneously.\n\n## Data Sources & Experimental Design\n\n*   **Timeframe**: January 1, 2024 to December 31, 2024 (365 days).\n*   **Location**: New Delhi, India (28.6°N, 77.1°E).\n*   **Astrology Engine**: Swiss Ephemeris (DE431) with Lahiri Ayanamsa.\n*   **Sampling Resolution**: Daily (numerology) and noon-time lunar position (astrology).\n\nWe intentionally use **daily sampling** to respect numerology's discrete granularity and compare it directly to the Moon's ruling Nakshatra lord.\n\n## Athlete Name + Birthdate Dataset\n\nTo test **name-based numerology** against **birth-based numerology**, we use a sampled athlete dataset with name and birth date fields (N=500). This enables correlation analysis between expression numbers and life-path numbers.\n\nDataset: `use_cases/numerology/research_paper/data/athletes_sample.csv` (source: @athletes_dataset_stat408)\n\n## Numerology Algorithm: Modulo-9 Arithmetic\n\nVedic numerology uses a base-9 system. The \"Mulanka\" (Root Number) is the most rapidly changing daily indicator. It is derived from the day of the month ($D$) using digital root summation, which is mathematically equivalent to modulo-9 arithmetic (with 9 replacing 0).\n\nThe algorithm for the Ruling Planet $P_{num}$ on day $D$ is:\n\n$$\nV = (D - 1) \\bmod 9 + 1\n$$\n\nWhere $V$ maps to the planet list: $\\{1 \\to Sun, 2 \\to Moon, \\dots, 9 \\to Mars\\}$.\nThis function is a **discrete step function** $f(t)$ that holds a constant integer value for 24 hours (or until the next calendar sunrise).\n\n## Astrology Algorithm: Continuous Celestial Mechanics\n\nVedic Astrology requires determining the precise position of planets on the Ecliptic. We utilize the **Swiss Ephemeris (DE431)** for high-precision calculations.\n\nThe continuous position function $\\lambda_p(t)$ for a planet $p$ at time $t$ involves:\n1.  **Heliocentric Calculation**: $r(t)$ vector from Sun to Planet.\n2.  **Geocentric Conversion**: Adjusting for Earth's position.\n3.  **Sidereal Adjustment (Ayanamsa)**: Subtracting the precession of equinoxes using the Lahiri Ayanamsa ($\\alpha \\approx 24^\\circ$).\n\n$$\n\\lambda_{sidereal}(t) = \\lambda_{tropical}(t) - \\alpha(t)\n$$\n\n### The Moon's Vital Role: Nakshatras\n\nThe Moon is the fastest-moving body, traversing the zodiac in ~27.3 days. In Vedic Astrology, the zodiac is divided into 27 **Nakshatras** (Lunar Mansions) of $13^\\circ 20'$ each.\n\nThe Nakshatra index $N$ is calculated as:\n\n$$\nN = \\lfloor \\frac{\\lambda_{Moon}}{13.333^\\circ} \\rfloor\n$$\n\nEach Nakshatra is ruled by a planet (Lord) in a specific sequence (Ketu $\\to$ Venus $\\to$ Sun...). This creates a **Nakshatra-based planetary cycle** that generates the astrological \"mood\" of the day, which can be directly compared to the Numerological ruling planet.\n\n## Derived Variables\n\nThe computational pipeline produces the following core variables per day:\n\n| Variable | Definition | Type |\n| --- | --- | --- |\n| `mulanka` | Digital root of day (1-9) | Discrete |\n| `numerology_lord` | Planet mapped from `mulanka` | Categorical |\n| `nakshatra_lord` | Planet ruling the Moon's Nakshatra | Categorical |\n| `match` | 1 if lords align, else 0 | Binary |\n\n## Methodology Pipeline & Algorithm\n\nThe full pipeline is designed to be deterministic and reproducible from raw dates and location.\n\n```{mermaid}\nflowchart TD\n  A[\"Date (YYYY-MM-DD)\"] --> B[\"Mulanka via digital root\"]\n  A --> C[\"Moon longitude (Swiss Ephemeris)\"]\n  C --> D[\"Nakshatra index\"]\n  D --> E[\"Nakshatra lord\"]\n  B --> F[\"Numerology lord\"]\n  F --> G[\"Match?\"]\n  E --> G\n  G --> H[\"Metrics + Figures\"]\n```\n\n**Algorithm 1: Daily Alignment Pipeline**\n\n1. **Input**: Date range, latitude, longitude, and ayanamsa system.\n2. **Compute Numerology**: For each date, compute Mulanka $V = (D-1) \\bmod 9 + 1$ and map to a numerology lord.\n3. **Compute Astrology**: For each date, compute Moon longitude at local noon and map to Nakshatra lord.\n4. **Align**: Record whether numerology lord equals Nakshatra lord.\n5. **Analyze**: Compute alignment rate, confusion matrix, monthly trends, and spectral signatures.\n\n# Data Analysis & Results\n\nWe analyzed the daily planetary status for the full year of 2024.\n\n\n\n## 1. The Temporal Mismatch\n\nThe graph below visualizes the fundamental disconnect. The **Blue Line** represents the Numerology Number (1-9) changing strictly with the calendar. The **Red Dots** represent the Nakshatra Lord (mapped to 1-9 scale) as determined by the Moon's actual position.\n\nNote the **irregularity** of the Red Dots compared to the **step-wise** Blue Line. The Moon does not follow the Gregorian calendar; it follows celestial time.\n\n::: {.cell fig-height='5' fig-width='10' execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![Temporal Discontinuity: Numerology (Blue) vs Astrology (Red) over 2 months](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-mismatch-output-1.png){#fig-mismatch fig-pos='H'}\n:::\n:::\n\n\n## 2. Distribution of Numerological vs Astrological Lords\n\nTo understand baseline behavior, we visualize how often each planet appears in both systems across the year.\n\n::: {.cell fig-height='5' fig-width='10' execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![Distribution of Numerology Lords vs Nakshatra Lords (2024)](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-distributions-output-1.png){#fig-distributions fig-pos='H'}\n:::\n:::\n\n\n## 3. Statistical Probability of Alignment\n\nIf these systems were synchronized, we would expect a high degree of matching. However, our analysis shows:\n\n::: {#stats .cell execution_count=5}\n\n::: {.cell-output .cell-output-stdout}\n```\nTotal Matches in 2024: 38/366\nSynchronization Rate: 10.38%\n```\n:::\n:::\n\n\nThe synchronization rate is approximately **${python} f\"{pct:.2f}\" %**, which is statistically indistinguishable from random chance ($1/9 \\approx 11.1\\%$). This confirms that **there is no inherent causal link** between the Gregorian date number and the actual lunar position.\n\n## 4. Confusion Matrix: Numerology vs Nakshatra Lord\n\nThe following heatmap shows how often each numerology lord coincides with each Nakshatra lord.\n\n::: {.cell fig-height='6' fig-width='7' execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![Confusion Matrix of Numerology vs Nakshatra Lords](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-confusion-output-1.png){#fig-confusion fig-pos='H'}\n:::\n:::\n\n\n## 5. Statistical Association Metrics\n\nWe quantify association strength using chi-square statistics, Cramer's V, and mutual information.\n\n::: {#stats-metrics .cell execution_count=7}\n\n::: {.cell-output .cell-output-stdout}\n```\nChi-square: 61.41 (df=64)\nCramer's V: 0.1448\nMutual Information: 0.0935\n```\n:::\n:::\n\n\n## 6. Alignment Over Time (Monthly)\n\nWe compute monthly alignment rates to check for seasonal or calendar patterns.\n\n::: {.cell fig-height='4' fig-width='9' execution_count=8}\n\n::: {.cell-output .cell-output-display}\n![Monthly Alignment Rate (2024)](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-monthly-output-1.png){#fig-monthly fig-pos='H'}\n:::\n:::\n\n\n## 7. Detailed Moon Phase Variation\n\nBeyond just the Nakshatra, the Moon's \"mood\" is heavily influenced by its phase (Paksha). Numerology treats every \"2\" (Moon number) day as identical. However, Astrology distinguishes between:\n*   **Shukla Paksha (Waxing)**: Growth, accumulation (Positive Moon).\n*   **Krishna Paksha (Waning)**: Decay, release (Negative/Weak Moon).\n\nThe following chart tracks the Moon's longitude over the year, showing the rapid, continuous cycle that numerology flattens into a single digit.\n\n::: {.cell fig-height='4' fig-width='10' execution_count=9}\n\n::: {.cell-output .cell-output-display}\n![The Continuous Wave: Moon's Journey through the Zodiac](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-moon-cycle-output-1.png){#fig-moon-cycle fig-pos='H'}\n:::\n:::\n\n\n## 8. Frequency-Domain Signature (Spectral Analysis)\n\nWe compare the frequency spectrum of numerology (discrete step function) vs. astrology (nakshatra lord changes).\n\n::: {.cell fig-height='4' fig-width='9' execution_count=10}\n\n::: {.cell-output .cell-output-display}\n![Frequency Domain: Numerology vs Nakshatra Lords](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-spectral-output-1.png){#fig-spectral fig-pos='H'}\n:::\n:::\n\n\n\\FloatBarrier\n\n# The Illusion of Strength: Pattern Repetition vs. Celestial Reality\n\nA common tenet in popular numerology is that **repetition equals strength**. It is assumed that dates with repeating numbers (e.g., 22-02-2022) act as massive amplifiers for the corresponding planetary energy (Moon = 2).\n\nWe tested this hypothesis by searching for **\"Divergence Dates\"**: days where a number appears frequently (High Numerological \"Strength\") but the actual planet is weak or debilitated in the sky.\n\n## Methodology\n\n1.  **Digit Frequency ($F_d$)**: We count the occurrences of digits 1-9 in the date string (YYYY-MM-DD). If $F_d \\ge 3$, we consider it a \"Numerologically Strong\" day for that number.\n2.  **Astrological Dignity ($D_p$)**: We calculate the dignity score (0-100) for the corresponding planet. If $D_p \\le 30$, we consider it \"Astrologically Weak\".\n3.  **Divergence**: A match occurs when $F_d \\ge 3$ AND $D_p \\le 30$.\n\n## Case Studies of Divergence\n\nThe following analysis scans our 5-year dataset to expose these illusions.\n\n::: {.cell tbl-cap='Critical Divergence Dates: High Repetition vs Low Strength' execution_count=11}\n\n::: {#divergence-analysis .cell-output .cell-output-display .cell-output-markdown}\n| Date       |   Number | Planet   | Repetition   | Astro State            |\n|:-----------|---------:|:---------|:-------------|:-----------------------|\n| 2024-02-02 |        2 | Moon     | 4 times      | Debilitated in Scorpio |\n| 2024-02-03 |        2 | Moon     | 3 times      | Debilitated in Scorpio |\n| 2024-02-29 |        2 | Moon     | 4 times      | Debilitated in Scorpio |\n| 2024-03-02 |        2 | Moon     | 3 times      | Debilitated in Scorpio |\n| 2024-03-27 |        2 | Moon     | 3 times      | Debilitated in Scorpio |\n| 2024-03-28 |        2 | Moon     | 3 times      | Debilitated in Scorpio |\n| 2024-03-29 |        2 | Moon     | 3 times      | Debilitated in Scorpio |\n| 2024-04-24 |        2 | Moon     | 3 times      | Debilitated in Scorpio |\n| 2024-04-25 |        2 | Moon     | 3 times      | Debilitated in Scorpio |\n| 2024-05-21 |        2 | Moon     | 3 times      | Debilitated in Scorpio |\n:::\n:::\n\n\n### Analysis of Findings\n\nThe table above (if populated) highlights dates where users might be misled by the calendar.\n\n**Hypothetical Example: The Moon in Scorpio Trap**\nIf the date `2022-02-22` (or similar) occurred while the Moon was in Scorpio (its sign of debilitation), numerology would predict a \"Dual Master Number\" day of immense intuition and connection (2). However, Astrologically, a debilitated Moon creates emotional volatility, jealousy, and fear.\n\n*   **Numerology says**: \"Connect, feel, unite.\"\n*   **Astrology says**: \"Protect your energy, avoid paranoia.\"\n\nThis **negative correlation** is dangerous. Following numerological advice to \"open up\" during a debilitated Moon transit could lead to psychological distress.\n\n# Robustness Checks\n\nWe test sensitivity to time-of-day and location. If numerology were genuinely synchronized with astrology, match rates should remain stable across observation conditions.\n\n::: {.cell tbl-cap='Robustness Checks: Match Rates Across Locations & Times' execution_count=12}\n\n::: {#robustness .cell-output .cell-output-display execution_count=11}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Location</th>\n      <th>Noon Match %</th>\n      <th>Midnight Match %</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>New Delhi</td>\n      <td>10.38</td>\n      <td>15.03</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Kathmandu</td>\n      <td>10.38</td>\n      <td>15.03</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>New York</td>\n      <td>10.38</td>\n      <td>15.03</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n# Ethical & Practical Considerations\n\nThis study evaluates symbolic systems using quantitative methods. Results should not be used to override medical, legal, or safety-critical decision-making. The objective is **methodological clarity**, not prescriptive or determinist prediction.\n\n# Limitations\n\n*   **Sampling Resolution**: Astrology varies hourly; our daily sampling compresses this variability.\n*   **Single-Year Data**: 2024 provides a clean baseline but does not cover multi-year cycles.\n*   **Simplified Dignity Checks**: Debilitation logic uses sign-based conditions only; full shadbala would refine this.\n*   **Cultural Variants**: Numerology traditions differ (Vedic vs. Pythagorean), which may affect mapping.\n\n# Reproducibility & Availability\n\n*   **Codebase**: All algorithms used in this paper are implemented in the repository under `src/`.\n*   **Data Generation**: Daily series are generated programmatically from Swiss Ephemeris.\n*   **Reproducibility Target**: Exact replication of 2024 results should be deterministic given identical settings.\n\n\\FloatBarrier\n\n# Reproducibility\n\nSee the reproducibility details and code references in the Methods and Robustness sections.\n\n# Conclusion\n\nThis study serves as a definitive resource for understanding the mechanics of Vedic predictive systems. By upgrading our analysis to include **Nakshatra algorithms** and **Lunar dynamics**, we have established:\n\n1.  **Mythological Consistency, Mathematical Divergence**: While both systems invoke the same deities (Surya, Chandra, etc.), their mathematical invocation of these deities occurs on disjoint timelines.\n2.  **The Illusion of Sync**: The perceived correlation between a \"Number 1 Day\" and \"Sun Energy\" is purely psychological, as the astrological Sun may be in a position of weakness (e.g., Libra) or darkness (Night) on that very day.\n3.  **Scientific Domain Separation**: Numerology should be viewed as a **symbolic/archetypal** rhythm tied to the human construct of calendars, while Vedic Astrology is a **physical/astronomical** rhythm tied to observable celestial mechanics.\n\nResearchers and practitioners must therefore treat these as independent variables in any predictive model, rather than assuming they reinforce each other.\n\n# References\n1. *BPHS (Brihat Parashara Hora Shastra)*. The foundational text of Vedic Astrology.\n2. *Swiss Ephemeris*. Documentation of astronomical algorithms.\n3. *Vedic Numerology (Anka Jyotish)*. Traditional principles of date reduction.\n\n# Numerology Principles Catalog\n\nThis section provides an **exhaustive catalog** of numerology principles included in the report: Lo Shu grid, Vedic numerology mapping, missing numbers, master numbers, karmic debt, compound numbers, date‑based transits, **name-based numerology** (Pythagorean and Chaldean mappings), plus personal cycles (Life Path, Destiny, Pinnacles, Challenges, Karmic Lessons, Hidden Passion).\n\n::: {.cell execution_count=13}\n\n::: {#num-catalog .cell-output .cell-output-display execution_count=12}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>combo_id</th>\n      <th>category</th>\n      <th>rule</th>\n      <th>parameters</th>\n      <th>number</th>\n      <th>count</th>\n      <th>planet</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>lo_shu:000001</td>\n      <td>lo_shu</td>\n      <td>Lo Shu position for 1</td>\n      <td>pos=(3, 1)</td>\n      <td>1.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>lo_shu:000002</td>\n      <td>lo_shu</td>\n      <td>Lo Shu position for 2</td>\n      <td>pos=(1, 3)</td>\n      <td>2.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>lo_shu:000003</td>\n      <td>lo_shu</td>\n      <td>Lo Shu position for 3</td>\n      <td>pos=(2, 3)</td>\n      <td>3.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>lo_shu:000004</td>\n      <td>lo_shu</td>\n      <td>Lo Shu position for 4</td>\n      <td>pos=(1, 2)</td>\n      <td>4.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>lo_shu:000005</td>\n      <td>lo_shu</td>\n      <td>Lo Shu position for 5</td>\n      <td>pos=(2, 2)</td>\n      <td>5.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>lo_shu:000006</td>\n      <td>lo_shu</td>\n      <td>Lo Shu position for 6</td>\n      <td>pos=(3, 2)</td>\n      <td>6.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>lo_shu:000007</td>\n      <td>lo_shu</td>\n      <td>Lo Shu position for 7</td>\n      <td>pos=(1, 1)</td>\n      <td>7.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>lo_shu:000008</td>\n      <td>lo_shu</td>\n      <td>Lo Shu position for 8</td>\n      <td>pos=(2, 1)</td>\n      <td>8.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>lo_shu:000009</td>\n      <td>lo_shu</td>\n      <td>Lo Shu position for 9</td>\n      <td>pos=(3, 3)</td>\n      <td>9.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>missing_number:000010</td>\n      <td>missing_number</td>\n      <td>Missing number 1</td>\n      <td>count=0</td>\n      <td>1.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>missing_number:000011</td>\n      <td>missing_number</td>\n      <td>Missing number 2</td>\n      <td>count=0</td>\n      <td>2.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>missing_number:000012</td>\n      <td>missing_number</td>\n      <td>Missing number 3</td>\n      <td>count=0</td>\n      <td>3.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>missing_number:000013</td>\n      <td>missing_number</td>\n      <td>Missing number 4</td>\n      <td>count=0</td>\n      <td>4.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>missing_number:000014</td>\n      <td>missing_number</td>\n      <td>Missing number 5</td>\n      <td>count=0</td>\n      <td>5.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>missing_number:000015</td>\n      <td>missing_number</td>\n      <td>Missing number 6</td>\n      <td>count=0</td>\n      <td>6.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>missing_number:000016</td>\n      <td>missing_number</td>\n      <td>Missing number 7</td>\n      <td>count=0</td>\n      <td>7.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>missing_number:000017</td>\n      <td>missing_number</td>\n      <td>Missing number 8</td>\n      <td>count=0</td>\n      <td>8.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>missing_number:000018</td>\n      <td>missing_number</td>\n      <td>Missing number 9</td>\n      <td>count=0</td>\n      <td>9.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>repetition:000019</td>\n      <td>repetition</td>\n      <td>Number 1 repeated 2 times</td>\n      <td>count=2</td>\n      <td>1.0</td>\n      <td>2.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>repetition:000020</td>\n      <td>repetition</td>\n      <td>Number 1 repeated 3 times</td>\n      <td>count=3</td>\n      <td>1.0</td>\n      <td>3.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>repetition:000021</td>\n      <td>repetition</td>\n      <td>Number 1 repeated 4 times</td>\n      <td>count=4</td>\n      <td>1.0</td>\n      <td>4.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>21</th>\n      <td>repetition:000022</td>\n      <td>repetition</td>\n      <td>Number 1 repeated 5 times</td>\n      <td>count=5</td>\n      <td>1.0</td>\n      <td>5.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>22</th>\n      <td>repetition:000023</td>\n      <td>repetition</td>\n      <td>Number 2 repeated 2 times</td>\n      <td>count=2</td>\n      <td>2.0</td>\n      <td>2.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>23</th>\n      <td>repetition:000024</td>\n      <td>repetition</td>\n      <td>Number 2 repeated 3 times</td>\n      <td>count=3</td>\n      <td>2.0</td>\n      <td>3.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>24</th>\n      <td>repetition:000025</td>\n      <td>repetition</td>\n      <td>Number 2 repeated 4 times</td>\n      <td>count=4</td>\n      <td>2.0</td>\n      <td>4.0</td>\n      <td>NaN</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.cell tbl-cap='Principle Counts by Category' execution_count=14}\n\n::: {#num-catalog-counts .cell-output .cell-output-display execution_count=13}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>category</th>\n      <th>count</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>2</th>\n      <td>compound_number</td>\n      <td>99</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>repetition</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>missing_number</td>\n      <td>9</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>pythagorean_mapping</td>\n      <td>9</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>transit_year</td>\n      <td>9</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>transit_month</td>\n      <td>9</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>transit_day</td>\n      <td>9</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>vedic_mapping</td>\n      <td>9</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>lo_shu</td>\n      <td>9</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>karmic_lesson</td>\n      <td>9</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>hidden_passion</td>\n      <td>9</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>chaldean_mapping</td>\n      <td>8</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>personal_number</td>\n      <td>6</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>challenge</td>\n      <td>4</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>pinnacle</td>\n      <td>4</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>karmic_debt</td>\n      <td>4</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>master_number</td>\n      <td>3</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n# Vedic Principles Coverage (Master Catalog)\n\nThe project maintains a shared **Vedic Principles Catalog** that enumerates the core and extended Jyotish concepts described in classical texts such as **BPHS**, **Brihat Samhita**, **Saravali**, **Jataka Parijata**, and **Surya Siddhanta**. This numerology report uses a focused subset (planetary lords, dignity, and nakshatra mapping) and documents the rest for completeness. This guarantees future expansion without altering the report structure. [@bphs; @varahamihira_brihat_samhita; @saravali; @jataka_parijata; @surya_siddhanta]\n\n::: {.cell fig-height='4' fig-width='8' execution_count=15}\n\n::: {.cell-output .cell-output-display}\n![Vedic Principles Catalog: Counts by Family](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/num-vedic-catalog-counts-output-1.png){#num-vedic-catalog-counts fig-pos='H'}\n:::\n:::\n\n\n::: {#tbl-num-vedic-coverage .cell tbl-cap='Coverage Matrix for Numerology Report' execution_count=16}\n\n::: {.cell-output .cell-output-display execution_count=15}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>coverage_status</th>\n      <th>family</th>\n      <th>scope</th>\n      <th>computed</th>\n      <th>documented</th>\n      <th>not_included</th>\n      <th>coverage_ratio</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>3</th>\n      <td>bhava</td>\n      <td>core</td>\n      <td>0</td>\n      <td>13</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>combustion</td>\n      <td>core</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>dignity</td>\n      <td>core</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>drishti</td>\n      <td>core</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>eclipse</td>\n      <td>core</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>graha</td>\n      <td>core</td>\n      <td>10</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>graha_yuddha</td>\n      <td>core</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>karana</td>\n      <td>core</td>\n      <td>0</td>\n      <td>12</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>nakshatra</td>\n      <td>core</td>\n      <td>28</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>rashi</td>\n      <td>core</td>\n      <td>13</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>retrograde</td>\n      <td>core</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>shadbala</td>\n      <td>core</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>syzygy</td>\n      <td>core</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>tithi</td>\n      <td>core</td>\n      <td>0</td>\n      <td>31</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>23</th>\n      <td>yoga</td>\n      <td>core</td>\n      <td>0</td>\n      <td>28</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>arudha</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>0</td>\n      <td>3</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>ashtakavarga</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>0</td>\n      <td>3</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>avastha</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>0</td>\n      <td>7</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>dasha</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>0</td>\n      <td>6</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>gocara</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>kala</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>muhurta</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>21</th>\n      <td>upagraha</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>0</td>\n      <td>6</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>22</th>\n      <td>varga</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>0</td>\n      <td>17</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>24</th>\n      <td>yoga_classical</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#tbl-num-vedic-master .cell tbl-cap='Master Vedic Principles Catalog (Core + Extended)' execution_count=17}\n\n::: {.cell-output .cell-output-display execution_count=16}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>family</th>\n      <th>item_type</th>\n      <th>name</th>\n      <th>scope</th>\n      <th>computable</th>\n      <th>description</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>arudha</td>\n      <td>family</td>\n      <td>Arudha (Pada)</td>\n      <td>extended</td>\n      <td>False</td>\n      <td>Reflection-based indicators of manifestation a...</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>arudha</td>\n      <td>member</td>\n      <td>Arudha Lagna</td>\n      <td>extended</td>\n      <td>False</td>\n      <td>Arudha concept: Arudha Lagna.</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>arudha</td>\n      <td>member</td>\n      <td>Bhava Arudha</td>\n      <td>extended</td>\n      <td>False</td>\n      <td>Arudha concept: Bhava Arudha.</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>ashtakavarga</td>\n      <td>family</td>\n      <td>Ashtakavarga</td>\n      <td>extended</td>\n      <td>False</td>\n      <td>Point-based evaluation of planetary contributi...</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>ashtakavarga</td>\n      <td>member</td>\n      <td>Bhinnashtakavarga</td>\n      <td>extended</td>\n      <td>False</td>\n      <td>Ashtakavarga method: Bhinnashtakavarga.</td>\n    </tr>\n    <tr>\n      <th>...</th>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n    </tr>\n    <tr>\n      <th>184</th>\n      <td>yoga</td>\n      <td>member</td>\n      <td>Vishkumbha</td>\n      <td>core</td>\n      <td>True</td>\n      <td>Yoga: Vishkumbha.</td>\n    </tr>\n    <tr>\n      <th>185</th>\n      <td>yoga</td>\n      <td>member</td>\n      <td>Vriddhi</td>\n      <td>core</td>\n      <td>True</td>\n      <td>Yoga: Vriddhi.</td>\n    </tr>\n    <tr>\n      <th>186</th>\n      <td>yoga</td>\n      <td>member</td>\n      <td>Vyaghata</td>\n      <td>core</td>\n      <td>True</td>\n      <td>Yoga: Vyaghata.</td>\n    </tr>\n    <tr>\n      <th>187</th>\n      <td>yoga</td>\n      <td>member</td>\n      <td>Vyatipata</td>\n      <td>core</td>\n      <td>True</td>\n      <td>Yoga: Vyatipata.</td>\n    </tr>\n    <tr>\n      <th>188</th>\n      <td>yoga_classical</td>\n      <td>family</td>\n      <td>Classical Yogas</td>\n      <td>extended</td>\n      <td>False</td>\n      <td>Combinational yogas such as Raja, Dhana, and A...</td>\n    </tr>\n  </tbody>\n</table>\n<p>189 rows × 6 columns</p>\n</div>\n```\n:::\n:::\n\n\n# Frequency & Distribution Graphs\n\nThis section plots **frequency and distribution** of numerological patterns (UDN/UMN/UYN, missing numbers).\n\n\n\n::: {.cell fig-height='4' fig-width='7.5' execution_count=19}\n\n::: {.cell-output .cell-output-display}\n![Universal Day Number (UDN) Frequency](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-udn-output-1.png){#fig-udn fig-pos='H'}\n:::\n:::\n\n\n::: {.cell fig-height='4' fig-width='7.5' execution_count=20}\n\n::: {.cell-output .cell-output-display}\n![Life Path Distribution (Birth Dataset)](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-life-path-output-1.png){#fig-life-path fig-pos='H'}\n:::\n:::\n\n\n::: {.cell fig-height='4' fig-width='7.5' execution_count=21}\n\n::: {.cell-output .cell-output-display}\n![Name-Based Expression Number Distribution (Pythagorean)](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-name-expression-output-1.png){#fig-name-expression fig-pos='H'}\n:::\n:::\n\n\n::: {.cell fig-height='4' fig-width='8' execution_count=22}\n\n::: {.cell-output .cell-output-display}\n![Missing Number Frequency (Lo Shu)](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-missing-output-1.png){#fig-missing fig-pos='H'}\n:::\n:::\n\n\n# Alignment & Window Graphs\n\nThis section compares **numerology transits** to astrological alignment windows and provides windowed overlap charts.\n\n::: {#fig-udn-monthly .cell fig-height='4' fig-width='8' execution_count=23}\n\n::: {#fig-udn-monthly-1 .cell-output .cell-output-display}\n```\n<Figure size 2700x1200 with 0 Axes>\n```\n\nMonthly UDN Distribution\n:::\n\n::: {.cell-output .cell-output-display}\n![](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-udn-monthly-output-2.png){#fig-udn-monthly-2 fig-pos='H'}\n:::\n:::\n\n\n::: {.cell fig-height='4' fig-width='8' execution_count=24}\n\n::: {.cell-output .cell-output-display}\n![Name-Based Soul Urge Distribution (Pythagorean vs Chaldean)](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-name-soul-urge-output-1.png){#fig-name-soul-urge fig-pos='H'}\n:::\n:::\n\n\n::: {.cell fig-height='4' fig-width='8' execution_count=25}\n\n::: {.cell-output .cell-output-display}\n![Pinnacle Distributions (Birth Dataset)](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-pinnacle-output-1.png){#fig-pinnacle fig-pos='H'}\n:::\n:::\n\n\n::: {.cell fig-height='4' fig-width='7.5' execution_count=26}\n\n::: {.cell-output .cell-output-display}\n![Name vs Birth Numerology Correlation (Athletes Sample)](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-athlete-correlation-output-1.png){#fig-athlete-correlation fig-pos='H'}\n:::\n:::\n\n\n\n\n::: {.cell fig-height='4' fig-width='8' execution_count=28}\n\n::: {.cell-output .cell-output-display}\n![Missing Number Heatmap by Month](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-missing-heatmap-output-1.png){#fig-missing-heatmap fig-pos='H'}\n:::\n:::\n\n\n# Individual Planet Variations (Annual Analysis)\n\nThis section presents the detailed daily traversal of each of the 9 Grahas (Planets) for the year 2024. \n\nFor each planet, we visualize:\n1.  **Top Chart (Astrological Reality)**: The continuous fluctuation of planetary dignity/strength (Shadbala-proxy) based on astronomical position, retrograde motion, and sign placement.\n2.  **Bottom Chart (Numerological Projection)**: The discrete \"influence\" as projected by daily numerology (Mulanka).\n\nThis direct visual comparison exposes the granularity mismatch: while the Planet (Top) moves in complex, non-linear harmonic waves, the Numerology (Bottom) forces a rigid, low-resolution step function.\n\n\n\n## The Sun (Surya) - Number 1\n\n::: {.cell execution_count=30}\n\n::: {.cell-output .cell-output-display}\n![Sun: Annual Transit vs Number 1 Days](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-var-sun-output-1.png){#fig-var-sun}\n:::\n:::\n\n\n\\newpage\n\n## The Moon (Chandra) - Number 2\n\n::: {.cell execution_count=31}\n\n::: {.cell-output .cell-output-display}\n![Moon: Monthly Cycles vs Number 2 Days](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-var-moon-output-1.png){#fig-var-moon}\n:::\n:::\n\n\n\\newpage\n\n## Jupiter (Brihaspati) - Number 3\n\n::: {.cell execution_count=32}\n\n::: {.cell-output .cell-output-display}\n![Jupiter: Annual Progress vs Number 3 Days](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-var-jupiter-output-1.png){#fig-var-jupiter}\n:::\n:::\n\n\n\\newpage\n\n## Rahu (North Node) - Number 4\n\n::: {.cell execution_count=33}\n\n::: {.cell-output .cell-output-display}\n![Rahu: 18-Year Cycle Component vs Number 4 Days](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-var-rahu-output-1.png){#fig-var-rahu}\n:::\n:::\n\n\n\\newpage\n\n## Mercury (Budha) - Number 5\n\n::: {.cell execution_count=34}\n\n::: {.cell-output .cell-output-display}\n![Mercury: Rapid Transits vs Number 5 Days](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-var-mercury-output-1.png){#fig-var-mercury}\n:::\n:::\n\n\n\\newpage\n\n## Venus (Shukra) - Number 6\n\n::: {.cell execution_count=35}\n\n::: {.cell-output .cell-output-display}\n![Venus: Transit Cycle vs Number 6 Days](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-var-venus-output-1.png){#fig-var-venus}\n:::\n:::\n\n\n\\newpage\n\n## Ketu (South Node) - Number 7\n\n::: {.cell execution_count=36}\n\n::: {.cell-output .cell-output-display}\n![Ketu: Karmic Axis vs Number 7 Days](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-var-ketu-output-1.png){#fig-var-ketu}\n:::\n:::\n\n\n\\newpage\n\n## Saturn (Shani) - Number 8\n\n::: {.cell execution_count=37}\n\n::: {.cell-output .cell-output-display}\n![Saturn: Slow Transit vs Number 8 Days](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-var-saturn-output-1.png){#fig-var-saturn}\n:::\n:::\n\n\n\\newpage\n\n## Mars (Mangal) - Number 9\n\n::: {.cell execution_count=38}\n\n::: {.cell-output .cell-output-display}\n![Mars: Energy Cycle vs Number 9 Days](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-var-mars-output-1.png){#fig-var-mars}\n:::\n:::\n\n\n\\newpage\n\n# Track 2: Earthquake Prediction Analysis\n\n# Overview\n\nThis report provides an **exhaustive Classical Jyotish Mundane** coverage for earthquake prediction claims. The intent is to **include every combination and trigger described in the classical corpus** so the analysis cannot be dismissed for missing principles. The report is organized as a modular catalogue, followed by algorithmic definitions and a large-scale empirical evaluation against the India-Nepal seismic dataset.\n\n## Scope Commitments\n\n- **All Classical Sources**: Brihat Samhita, BPHS, Surya Siddhanta, Jataka Parijata, Saravali.\n- **All Combination Classes**: malefic aspects, conjunctions, Graha Yuddha, Shadbala components, combustion, retrograde, nakshatra lords, Panchanga elements (tithi/karana/yoga), houses and signs, eclipses and syzygy windows.\n- **All Time Windows**: same-day, ±1, ±3, ±7, ±14, ±30 days around seismic events.\n- **All Results Reported**: frequency, event-alignment rate, and statistical significance where applicable.\n\n## Structure\n\n1. **Sources**: Classical texts and canonical principles.\n2. **Taxonomy**: A formal ontology of all trigger classes and variables.\n3. **Combination Catalog**: Machine-generated, exhaustive list with stable IDs.\n4. **Algorithms & Examples**: Formal definitions and step-by-step calculations.\n5. **Graphs & Results**: Frequency and alignment diagnostics for every category.\n6. **Appendix**: Full definitions and parameter defaults.\n\n# Classical Sources\n\nThis section enumerates the authoritative classical sources used as **primary references** for mundane astrology principles included in this report.\n\n## Covered Sources (Primary Canon)\n\n- **Brihat Samhita** [@varahamihira_brihat_samhita]\n- **Brihat Parashara Hora Shastra (BPHS)** [@bphs]\n- **Surya Siddhanta** [@surya_siddhanta]\n- **Jataka Parijata** [@jataka_parijata]\n- **Saravali** [@saravali]\n\n## Coverage Policy\n\nAll mundane principles that can be translated into **testable astronomical combinations** are included. If a classical rule is symbolic or qualitative, it is still recorded in the catalog with a note describing the limitation.\n\n# Mundane Jyotish Taxonomy (Exhaustive Scope)\n\nThis section defines the **complete combination space** used in the report. All combinations are derived from the canonical sources listed in Section 1 and formalized into a machine-readable taxonomy.\n\n## Core Entities\n\n- **Planets (Grahas)**: Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu, Ketu.\n- **Lunar Elements**: Tithi, Nakshatra, Karana, Yoga.\n- **Houses (Bhavas)**: 1–12 with emphasis on 4th (land), 8th (catastrophe), 12th (loss).\n- **Signs (Rashi)**: 12 zodiac signs (sidereal).\n- **Angular Relations**: Conjunction (0°), square (90°), opposition (180°), trine (120°), sextile (60°).\n- **Temporal Windows**: {0, ±1, ±3, ±7, ±14, ±30} days.\n\n## Combination Classes (All Included)\n\n1. **Malefic Aspects**: Mars/Saturn/Rahu/Ketu hard aspects.\n2. **Graha Yuddha**: Close conjunctions (<1°) between any pair.\n3. **Shadbala Components**: Each component and total combined strength.\n4. **Combustion & Retrograde**: Planet visibility and motion states.\n5. **Eclipses & Syzygy**: Solar/lunar eclipses; new/full moon windows.\n6. **Nakshatra Lords**: Lunar mansion rulerships and transitions.\n7. **House/Sign Triggers**: Malefics in critical houses or signs.\n8. **Panchanga**: Tithi/Karana/Yoga combinations.\n9. **Compound Rules**: Multi-factor conjunctions (e.g., Mars+Saturn conjunction during eclipse window in 4th house).\n\n## Ontology Fields (Catalog Columns)\n\n| Field | Description |\n| --- | --- |\n| `combo_id` | Stable unique ID |\n| `category` | Combination class |\n| `rule` | Formal rule definition |\n| `window_days` | Event window |\n| `sources` | Classical references |\n| `parameters` | Orbs, thresholds, rule-specific values |\n\n## Formal Notation\n\n- **Planetary longitude**: $\\lambda_p(t)$\n- **Aspect condition**: $|\\lambda_i - \\lambda_j| \\in \\{0°, 60°, 90°, 120°, 180°\\} \\pm \\epsilon$\n- **Conjunction (Graha Yuddha)**: $|\\lambda_i - \\lambda_j| < 1°$\n- **Combustion**: $|\\lambda_p - \\lambda_{Sun}| < 8°$\n- **Retrograde**: $\\dot{\\lambda}_p(t) < 0$\n\n## Combination Explosion Control\n\nTo ensure “all combinations” is **computationally tractable**, we define a complete but finite rule system:\n\n- All planet pairs/triples within the rule set.\n- All major aspects with configurable orbs.\n- All critical houses and signs with malefic occupancy.\n- All Panchanga elements for daily classification.\n- All defined time windows.\n\nThe master catalog is generated from these rules, guaranteeing exhaustive coverage without ambiguity.\n\n# Vedic Principles Coverage (Master Catalog)\n\nThis report anchors its methodology in a shared **Vedic Principles Catalog** derived from classical Jyotish sources. Every computable principle is enumerated and mapped to a reproducible algorithm; non-computable rules are still documented to maintain completeness and avoid selective omission. [@bphs; @varahamihira_brihat_samhita; @saravali; @jataka_parijata; @surya_siddhanta]\n\n::: {.cell fig-height='4' fig-width='8' execution_count=39}\n\n::: {.cell-output .cell-output-display}\n![Vedic Principles Catalog: Counts by Family](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/eq-vedic-catalog-counts-output-1.png){#eq-vedic-catalog-counts fig-pos='H'}\n:::\n:::\n\n\n::: {#tbl-eq-vedic-coverage .cell tbl-cap='Coverage Matrix for Earthquake Report' execution_count=40}\n\n::: {.cell-output .cell-output-display execution_count=39}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>coverage_status</th>\n      <th>family</th>\n      <th>scope</th>\n      <th>computed</th>\n      <th>documented</th>\n      <th>not_included</th>\n      <th>coverage_ratio</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>3</th>\n      <td>bhava</td>\n      <td>core</td>\n      <td>13</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>combustion</td>\n      <td>core</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>dignity</td>\n      <td>core</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>drishti</td>\n      <td>core</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>eclipse</td>\n      <td>core</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>graha</td>\n      <td>core</td>\n      <td>10</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>graha_yuddha</td>\n      <td>core</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>karana</td>\n      <td>core</td>\n      <td>12</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>nakshatra</td>\n      <td>core</td>\n      <td>28</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>rashi</td>\n      <td>core</td>\n      <td>13</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>retrograde</td>\n      <td>core</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>shadbala</td>\n      <td>core</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>syzygy</td>\n      <td>core</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>tithi</td>\n      <td>core</td>\n      <td>31</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>23</th>\n      <td>yoga</td>\n      <td>core</td>\n      <td>28</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>arudha</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>3</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>ashtakavarga</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>3</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>avastha</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>7</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>dasha</td>\n      <td>extended</td>\n      <td>6</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>gocara</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>kala</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>muhurta</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>21</th>\n      <td>upagraha</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>6</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>22</th>\n      <td>varga</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>17</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>24</th>\n      <td>yoga_classical</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#tbl-eq-vedic-master .cell tbl-cap='Master Vedic Principles Catalog (Core + Extended)' execution_count=41}\n\n::: {.cell-output .cell-output-display execution_count=40}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>family</th>\n      <th>item_type</th>\n      <th>name</th>\n      <th>scope</th>\n      <th>computable</th>\n      <th>description</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>arudha</td>\n      <td>family</td>\n      <td>Arudha (Pada)</td>\n      <td>extended</td>\n      <td>False</td>\n      <td>Reflection-based indicators of manifestation a...</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>arudha</td>\n      <td>member</td>\n      <td>Arudha Lagna</td>\n      <td>extended</td>\n      <td>False</td>\n      <td>Arudha concept: Arudha Lagna.</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>arudha</td>\n      <td>member</td>\n      <td>Bhava Arudha</td>\n      <td>extended</td>\n      <td>False</td>\n      <td>Arudha concept: Bhava Arudha.</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>ashtakavarga</td>\n      <td>family</td>\n      <td>Ashtakavarga</td>\n      <td>extended</td>\n      <td>False</td>\n      <td>Point-based evaluation of planetary contributi...</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>ashtakavarga</td>\n      <td>member</td>\n      <td>Bhinnashtakavarga</td>\n      <td>extended</td>\n      <td>False</td>\n      <td>Ashtakavarga method: Bhinnashtakavarga.</td>\n    </tr>\n    <tr>\n      <th>...</th>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n    </tr>\n    <tr>\n      <th>184</th>\n      <td>yoga</td>\n      <td>member</td>\n      <td>Vishkumbha</td>\n      <td>core</td>\n      <td>True</td>\n      <td>Yoga: Vishkumbha.</td>\n    </tr>\n    <tr>\n      <th>185</th>\n      <td>yoga</td>\n      <td>member</td>\n      <td>Vriddhi</td>\n      <td>core</td>\n      <td>True</td>\n      <td>Yoga: Vriddhi.</td>\n    </tr>\n    <tr>\n      <th>186</th>\n      <td>yoga</td>\n      <td>member</td>\n      <td>Vyaghata</td>\n      <td>core</td>\n      <td>True</td>\n      <td>Yoga: Vyaghata.</td>\n    </tr>\n    <tr>\n      <th>187</th>\n      <td>yoga</td>\n      <td>member</td>\n      <td>Vyatipata</td>\n      <td>core</td>\n      <td>True</td>\n      <td>Yoga: Vyatipata.</td>\n    </tr>\n    <tr>\n      <th>188</th>\n      <td>yoga_classical</td>\n      <td>family</td>\n      <td>Classical Yogas</td>\n      <td>extended</td>\n      <td>False</td>\n      <td>Combinational yogas such as Raja, Dhana, and A...</td>\n    </tr>\n  </tbody>\n</table>\n<p>189 rows × 6 columns</p>\n</div>\n```\n:::\n:::\n\n\n# Malefics, Aspects, and Angular Stress\n\nClassical mundane astrology emphasizes malefic angular relationships as destabilizing triggers [@bphs; @varahamihira_brihat_samhita].\n\n## Malefic Set\n\nWe define malefics as:\n\n**Mars, Saturn, Rahu, Ketu**\n\n## Aspect Definitions\n\nAll **major aspects** are included:\n\n- Conjunction (0°)\n- Sextile (60°)\n- Square (90°)\n- Trine (120°)\n- Opposition (180°)\n\n## Formal Rule\n\nFor planet pair $(i,j)$ and aspect angle $\\theta$:\n\n$$\n|(\\lambda_i - \\lambda_j) \\bmod 360 - \\theta| \\leq \\epsilon\n$$\n\nWe evaluate all orbs $\\epsilon \\in \\{1^\\circ, 3^\\circ, 5^\\circ, 8^\\circ\\}$.\n\n## Exhaustive Coverage\n\nAll malefic–malefic, malefic–benefic, and all-planet pairs are enumerated in the Master Combination Catalog.\n\n# Conjunctions and Graha Yuddha\n\nClassical texts describe **Graha Yuddha** (planetary war) as a critical indicator when two planets occupy nearly the same longitude [@bphs].\n\n## Conjunction Rule\n\nFor any planet pair $(i,j)$:\n\n$$\n|\\lambda_i - \\lambda_j| \\leq \\epsilon\n$$\n\nWe evaluate conjunctions at multiple orbs, and Graha Yuddha specifically at **1°**.\n\n## Exhaustive Coverage\n\nAll planet pairs are tested. Malefic-only conjunctions are highlighted as a dedicated subset in the catalog.\n\n# Shadbala Components (Sixfold Strength)\n\nShadbala is a composite measure of planetary strength described in classical Jyotish [@bphs]. We include each component and the total aggregated score.\n\n## Components\n\n1. **Sthana Bala** (positional)\n2. **Dig Bala** (directional)\n3. **Kala Bala** (temporal)\n4. **Chesta Bala** (motional)\n5. **Naisargika Bala** (natural)\n6. **Drik Bala** (aspectual)\n\n## Rule Bands\n\nEach planet is categorized into **low / medium / high** strength bands:\n\n- Low: 0–33\n- Medium: 34–66\n- High: 67–100\n\nThese bands are applied to **all planets** daily.\n\n# Combustion, Retrograde, and Visibility\n\nCombustion and retrograde status are classical modifiers of planetary efficacy [@bphs].\n\n## Combustion\n\nA planet is combust when within a defined orb of the Sun. We use **8°** as the standard orb:\n\n$$\n|\\lambda_p - \\lambda_{Sun}| < 8^\\circ\n$$\n\n## Retrograde\n\nA planet is retrograde when its longitudinal speed is negative:\n\n$$\n\\dot{\\lambda}_p(t) < 0\n$$\n\nAll planets are evaluated daily for both conditions.\n\n# Vimshottari Dasha Overlay (India + Nepal)\n\nTo address **phase‑2 country‑specific triggers**, we overlay the **India Independence Chart** (1947‑08‑15 00:00 IST, Delhi) and a **Nepal reference chart** (2015‑09‑20 00:00 NPT, Kathmandu) and compute the active **Vimshottari Mahadasha** for each day in the earthquake dataset. This allows the analysis to test whether regional dasha cycles contribute to event clustering beyond the global planetary configurations. [@bphs]\n\n::: {#fig-eq-dasha-days .cell fig-height='4' fig-width='7' execution_count=42}\n\n::: {#fig-eq-dasha-days-1 .cell-output .cell-output-display}\n```\n<Figure size 2100x1200 with 0 Axes>\n```\n\nIndia vs Nepal Vimshottari Mahadasha: Day Counts\n:::\n\n::: {.cell-output .cell-output-display}\n![](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-eq-dasha-days-output-2.png){#fig-eq-dasha-days-2 fig-pos='H'}\n:::\n:::\n\n\n::: {.cell fig-height='4' fig-width='8' execution_count=43}\n\n::: {.cell-output .cell-output-display}\n![Mahadasha Timeline: India vs Nepal (2015-2024)](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-eq-dasha-timeline-output-1.png){#fig-eq-dasha-timeline fig-pos='H'}\n:::\n:::\n\n\n::: {.cell fig-height='5' fig-width='6.5' execution_count=44}\n\n::: {.cell-output .cell-output-display}\n![Mahadasha Co-Occurrence: India vs Nepal](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-eq-dasha-heatmap-output-1.png){#fig-eq-dasha-heatmap fig-pos='H'}\n:::\n:::\n\n\n::: {.cell fig-height='5' fig-width='6.5' execution_count=45}\n\n::: {.cell-output .cell-output-display}\n![Antardasha Co-Occurrence: India vs Nepal](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-eq-antardasha-heatmap-output-1.png){#fig-eq-antardasha-heatmap fig-pos='H'}\n:::\n:::\n\n\n# Eclipses, Syzygy, and Temporal Windows\n\nClassical texts emphasize eclipse windows and syzygy as periods of heightened instability [@surya_siddhanta; @varahamihira_brihat_samhita].\n\n## Syzygy\n\n- **New Moon (Amavasya)**: $Tithi = 30$\n- **Full Moon (Purnima)**: $Tithi = 15$\n\n## Eclipse Proxy\n\nWe flag eclipse windows when syzygy coincides with proximity to lunar nodes (Rahu/Ketu):\n\n$$\n\\min(|\\lambda_{Moon}-\\lambda_{Rahu}|, |\\lambda_{Moon}-\\lambda_{Ketu}|) \\leq 12^\\circ\n$$\n\n## Windows\n\nAll combinations are evaluated in time windows: **0, ±1, ±3, ±7, ±14, ±30 days**.\n\n# Nakshatra-Based Mundane Triggers\n\nThe Moon’s Nakshatra lord is used as a daily classifier of cosmic mood [@bphs]. We evaluate all **9 planetary lords** across the full date range.\n\n## Rule\n\n$$\nNakshatraLord = f(\\lambda_{Moon})\n$$\n\nEach Nakshatra is mapped to its classical ruler; all lords are included in the catalog.\n\n# Houses, Signs, and Bhava-Based Mundane Rules\n\nClassical mundane astrology associates specific houses with land stability and catastrophe [@bphs]. We test **all planet-in-house** and **planet-in-sign** combinations, with emphasis on critical houses (4, 8, 12).\n\n## House Occupancy\n\nFor each planet $p$:\n\n$$\nHouse(p) = \\left\\lfloor \\frac{(\\lambda_p - \\lambda_{Asc}) \\bmod 360}{30} \\right\\rfloor + 1\n$$\n\n## Sign Occupancy\n\nEach planet’s zodiac sign is derived from its longitude and mapped to the sidereal sign index.\n\n## Coverage\n\nAll planets × all houses and signs are enumerated in the master catalog.\n\n# Yogas, Tithi, Karana, and Panchanga Combinations\n\nPanchanga elements are daily time-structure variables derived from Sun–Moon dynamics [@surya_siddhanta]. All combinations are included.\n\n## Tithi\n\n$$\nTithi = \\left\\lfloor \\frac{(\\lambda_{Moon}-\\lambda_{Sun}) \\bmod 360}{12} \\right\\rfloor + 1\n$$\n\n## Karana\n\n$$\nKaranaIndex = \\left\\lfloor \\frac{(\\lambda_{Moon}-\\lambda_{Sun}) \\bmod 360}{6} \\right\\rfloor + 1\n$$\n\n## Yoga\n\n$$\nYoga = \\left\\lfloor \\frac{(\\lambda_{Moon}+\\lambda_{Sun}) \\bmod 360}{13.3333} \\right\\rfloor + 1\n$$\n\nAll 30 tithis, 11 karana types, and 27 yogas are enumerated in the catalog.\n\n# Master Combination Catalog\n\nThis section presents the **exhaustive combination catalog**, generated programmatically from the taxonomy. Each rule has a stable ID for reproducibility and downstream graphing.\n\n::: {.cell execution_count=46}\n\n::: {#combo-catalog .cell-output .cell-output-display execution_count=45}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>combo_id</th>\n      <th>category</th>\n      <th>rule</th>\n      <th>parameters</th>\n      <th>window_days</th>\n      <th>sources</th>\n      <th>p1</th>\n      <th>p2</th>\n      <th>aspect</th>\n      <th>aspect_deg</th>\n      <th>...</th>\n      <th>tithi</th>\n      <th>karana</th>\n      <th>yoga</th>\n      <th>eclipse_type</th>\n      <th>phase</th>\n      <th>lord</th>\n      <th>sub_lord</th>\n      <th>india_lord</th>\n      <th>nepal_lord</th>\n      <th>compound</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>aspects:000001</td>\n      <td>aspects</td>\n      <td>Aspect conjunction between Sun and Moon</td>\n      <td>angle=0±1°</td>\n      <td>NaN</td>\n      <td>Brihat Samhita; BPHS; Surya Siddhanta; Jataka ...</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>conjunction</td>\n      <td>0.0</td>\n      <td>...</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>aspects:000002</td>\n      <td>aspects</td>\n      <td>Aspect conjunction between Sun and Moon</td>\n      <td>angle=0±3°</td>\n      <td>NaN</td>\n      <td>Brihat Samhita; BPHS; Surya Siddhanta; Jataka ...</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>conjunction</td>\n      <td>0.0</td>\n      <td>...</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>aspects:000003</td>\n      <td>aspects</td>\n      <td>Aspect conjunction between Sun and Moon</td>\n      <td>angle=0±5°</td>\n      <td>NaN</td>\n      <td>Brihat Samhita; BPHS; Surya Siddhanta; Jataka ...</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>conjunction</td>\n      <td>0.0</td>\n      <td>...</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>aspects:000004</td>\n      <td>aspects</td>\n      <td>Aspect conjunction between Sun and Moon</td>\n      <td>angle=0±8°</td>\n      <td>NaN</td>\n      <td>Brihat Samhita; BPHS; Surya Siddhanta; Jataka ...</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>conjunction</td>\n      <td>0.0</td>\n      <td>...</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>aspects:000005</td>\n      <td>aspects</td>\n      <td>Aspect sextile between Sun and Moon</td>\n      <td>angle=60±1°</td>\n      <td>NaN</td>\n      <td>Brihat Samhita; BPHS; Surya Siddhanta; Jataka ...</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>sextile</td>\n      <td>60.0</td>\n      <td>...</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>aspects:000006</td>\n      <td>aspects</td>\n      <td>Aspect sextile between Sun and Moon</td>\n      <td>angle=60±3°</td>\n      <td>NaN</td>\n      <td>Brihat Samhita; BPHS; Surya Siddhanta; Jataka ...</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>sextile</td>\n      <td>60.0</td>\n      <td>...</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>aspects:000007</td>\n      <td>aspects</td>\n      <td>Aspect sextile between Sun and Moon</td>\n      <td>angle=60±5°</td>\n      <td>NaN</td>\n      <td>Brihat Samhita; BPHS; Surya Siddhanta; Jataka ...</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>sextile</td>\n      <td>60.0</td>\n      <td>...</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>aspects:000008</td>\n      <td>aspects</td>\n      <td>Aspect sextile between Sun and Moon</td>\n      <td>angle=60±8°</td>\n      <td>NaN</td>\n      <td>Brihat Samhita; BPHS; Surya Siddhanta; Jataka ...</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>sextile</td>\n      <td>60.0</td>\n      <td>...</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>aspects:000009</td>\n      <td>aspects</td>\n      <td>Aspect square between Sun and Moon</td>\n      <td>angle=90±1°</td>\n      <td>NaN</td>\n      <td>Brihat Samhita; BPHS; Surya Siddhanta; Jataka ...</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>square</td>\n      <td>90.0</td>\n      <td>...</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>aspects:000010</td>\n      <td>aspects</td>\n      <td>Aspect square between Sun and Moon</td>\n      <td>angle=90±3°</td>\n      <td>NaN</td>\n      <td>Brihat Samhita; BPHS; Surya Siddhanta; Jataka ...</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>square</td>\n      <td>90.0</td>\n      <td>...</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>aspects:000011</td>\n      <td>aspects</td>\n      <td>Aspect square between Sun and Moon</td>\n      <td>angle=90±5°</td>\n      <td>NaN</td>\n      <td>Brihat Samhita; BPHS; Surya Siddhanta; Jataka ...</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>square</td>\n      <td>90.0</td>\n      <td>...</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>aspects:000012</td>\n      <td>aspects</td>\n      <td>Aspect square between Sun and Moon</td>\n      <td>angle=90±8°</td>\n      <td>NaN</td>\n      <td>Brihat Samhita; BPHS; Surya Siddhanta; Jataka ...</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>square</td>\n      <td>90.0</td>\n      <td>...</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>aspects:000013</td>\n      <td>aspects</td>\n      <td>Aspect trine between Sun and Moon</td>\n      <td>angle=120±1°</td>\n      <td>NaN</td>\n      <td>Brihat Samhita; BPHS; Surya Siddhanta; Jataka ...</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>trine</td>\n      <td>120.0</td>\n      <td>...</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>aspects:000014</td>\n      <td>aspects</td>\n      <td>Aspect trine between Sun and Moon</td>\n      <td>angle=120±3°</td>\n      <td>NaN</td>\n      <td>Brihat Samhita; BPHS; Surya Siddhanta; Jataka ...</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>trine</td>\n      <td>120.0</td>\n      <td>...</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>aspects:000015</td>\n      <td>aspects</td>\n      <td>Aspect trine between Sun and Moon</td>\n      <td>angle=120±5°</td>\n      <td>NaN</td>\n      <td>Brihat Samhita; BPHS; Surya Siddhanta; Jataka ...</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>trine</td>\n      <td>120.0</td>\n      <td>...</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>aspects:000016</td>\n      <td>aspects</td>\n      <td>Aspect trine between Sun and Moon</td>\n      <td>angle=120±8°</td>\n      <td>NaN</td>\n      <td>Brihat Samhita; BPHS; Surya Siddhanta; Jataka ...</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>trine</td>\n      <td>120.0</td>\n      <td>...</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>aspects:000017</td>\n      <td>aspects</td>\n      <td>Aspect opposition between Sun and Moon</td>\n      <td>angle=180±1°</td>\n      <td>NaN</td>\n      <td>Brihat Samhita; BPHS; Surya Siddhanta; Jataka ...</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>opposition</td>\n      <td>180.0</td>\n      <td>...</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>aspects:000018</td>\n      <td>aspects</td>\n      <td>Aspect opposition between Sun and Moon</td>\n      <td>angle=180±3°</td>\n      <td>NaN</td>\n      <td>Brihat Samhita; BPHS; Surya Siddhanta; Jataka ...</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>opposition</td>\n      <td>180.0</td>\n      <td>...</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>aspects:000019</td>\n      <td>aspects</td>\n      <td>Aspect opposition between Sun and Moon</td>\n      <td>angle=180±5°</td>\n      <td>NaN</td>\n      <td>Brihat Samhita; BPHS; Surya Siddhanta; Jataka ...</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>opposition</td>\n      <td>180.0</td>\n      <td>...</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>aspects:000020</td>\n      <td>aspects</td>\n      <td>Aspect opposition between Sun and Moon</td>\n      <td>angle=180±8°</td>\n      <td>NaN</td>\n      <td>Brihat Samhita; BPHS; Surya Siddhanta; Jataka ...</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>opposition</td>\n      <td>180.0</td>\n      <td>...</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n  </tbody>\n</table>\n<p>20 rows × 24 columns</p>\n</div>\n```\n:::\n:::\n\n\n::: {.cell tbl-cap='Combination Counts by Category' execution_count=47}\n\n::: {#combo-counts .cell-output .cell-output-display execution_count=46}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>category</th>\n      <th>count</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>aspects</td>\n      <td>720</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>malefic_aspects</td>\n      <td>120</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>sign</td>\n      <td>108</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>house</td>\n      <td>108</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>india_nepal_dasha_pair</td>\n      <td>81</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>india_nepal_antardasha_pair</td>\n      <td>81</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>graha_yuddha</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>tithi</td>\n      <td>30</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>shadbala</td>\n      <td>27</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>yoga</td>\n      <td>27</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>karana</td>\n      <td>11</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>combustion</td>\n      <td>9</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>india_dasha</td>\n      <td>9</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>nakshatra</td>\n      <td>9</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>nepal_antardasha</td>\n      <td>9</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>nepal_dasha</td>\n      <td>9</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>retrograde</td>\n      <td>9</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>india_antardasha</td>\n      <td>9</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>compound</td>\n      <td>6</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>eclipse</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>syzygy</td>\n      <td>2</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe full catalog is stored at `docs/research/track_2_earthquake_prediction/data/combination_catalog.csv`.\n\n# Frequency Graphs (All Combinations)\n\nThis section plots **activation frequencies** for every combination in the catalog.\n\n\n\n::: {.cell fig-height='4.5' fig-width='8.5' execution_count=49}\n\n::: {.cell-output .cell-output-display}\n![Activation Days by Combination Category](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-category-activation-output-1.png){#fig-category-activation fig-pos='H'}\n:::\n:::\n\n\n::: {.cell fig-height='6' fig-width='8.5' execution_count=50}\n\n::: {.cell-output .cell-output-display}\n![Top 25 Most Frequent Combinations](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-top-activation-output-1.png){#fig-top-activation fig-pos='H'}\n:::\n:::\n\n\n# Alignment Windows vs Earthquakes\n\nThis section compares **combination activation** against earthquake windows (same day and ±N days).\n\n::: {.cell fig-height='4.5' fig-width='8' execution_count=51}\n\n::: {.cell-output .cell-output-display}\n![Average Overlap Rate by Category (±3 days)](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-window-overlap-output-1.png){#fig-window-overlap fig-pos='H'}\n:::\n:::\n\n\n\n\n::: {.cell fig-height='4' fig-width='7.5' execution_count=53}\n\n::: {.cell-output .cell-output-display}\n![Z-score Distribution vs Random Baseline (±3 days)](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-earthquake-zscores-output-1.png){#fig-earthquake-zscores fig-pos='H'}\n:::\n:::\n\n\n::: {.cell fig-height='4.5' fig-width='8' execution_count=54}\n\n::: {.cell-output .cell-output-display}\n![Overlap Rates by Window Size (All Combinations)](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-window-compare-output-1.png){#fig-window-compare fig-pos='H'}\n:::\n:::\n\n\n::: {.cell fig-height='6' fig-width='8.5' execution_count=55}\n\n::: {.cell-output .cell-output-display}\n![Top 25 Combinations by ±3 Day Overlap](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-top-overlap-output-1.png){#fig-top-overlap fig-pos='H'}\n:::\n:::\n\n\n# Discussion, Limitations, and Interpretive Notes\n\nThis report aims for **exhaustive classical coverage**. The combination catalog is exhaustive within the defined ontology, but any rule not expressible in astronomical terms is documented qualitatively rather than computed.\n\n## Limitations\n\n- Some classical rules are symbolic and do not map cleanly to numerical thresholds.\n- House-based rules depend on a chosen location and time reference; we use the regional centroid at local noon for daily evaluation.\n- “All combinations” grows rapidly; we present aggregated results and provide machine-readable tables for inspection.\n\n## Interpretation Policy\n\nWe do not treat any alignment as causal. All findings are evaluated against baseline earthquake rates and statistical noise floors.\n\n# Appendix: Full Definitions and Formulae\n\nThis appendix enumerates all formulae, thresholds, and default parameters used in combination generation and evaluation.\n\n- Orb sets: {1°, 3°, 5°, 8°}\n- Eclipse node proximity: 12°\n- Syzygy tithis: 15 (Full), 30 (New)\n- Window sizes: {0, ±1, ±3, ±7, ±14, ±30 days}\n\nAll generated tables:\n\n- `docs/research/track_2_earthquake_prediction/data/combination_catalog.csv`\n- `docs/research/track_2_earthquake_prediction/data/daily_astro_base.csv`\n- `docs/research/track_2_earthquake_prediction/data/combination_metrics.csv`\n\n\n\n\\newpage\n\n# Track 3: Gold Market Correlation\n\n# Overview\n\nThis section summarizes scope, objectives, and the full astrology-principles coverage (Vedic + Western).\n\n# Astrology Principles Catalog (Vedic + Western)\n\nThis section provides an **exhaustive catalog** of astrology‑based indicators used for gold price prediction claims (Vedic + Western).\n\n::: {.cell execution_count=56}\n\n::: {#gold-astro-catalog .cell-output .cell-output-display execution_count=55}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>combo_id</th>\n      <th>category</th>\n      <th>rule</th>\n      <th>parameters</th>\n      <th>sources</th>\n      <th>p1</th>\n      <th>p2</th>\n      <th>aspect</th>\n      <th>aspect_deg</th>\n      <th>orb</th>\n      <th>sign</th>\n      <th>phase</th>\n      <th>eclipse_type</th>\n      <th>lord</th>\n      <th>window_days</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>major_aspect:000001</td>\n      <td>major_aspect</td>\n      <td>Sun-Moon conjunction</td>\n      <td>angle=0±1°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>conjunction</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>major_aspect:000002</td>\n      <td>major_aspect</td>\n      <td>Sun-Moon conjunction</td>\n      <td>angle=0±3°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>conjunction</td>\n      <td>0.0</td>\n      <td>3.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>major_aspect:000003</td>\n      <td>major_aspect</td>\n      <td>Sun-Moon conjunction</td>\n      <td>angle=0±5°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>conjunction</td>\n      <td>0.0</td>\n      <td>5.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>major_aspect:000004</td>\n      <td>major_aspect</td>\n      <td>Sun-Moon conjunction</td>\n      <td>angle=0±8°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>conjunction</td>\n      <td>0.0</td>\n      <td>8.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>major_aspect:000005</td>\n      <td>major_aspect</td>\n      <td>Sun-Moon sextile</td>\n      <td>angle=60±1°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>sextile</td>\n      <td>60.0</td>\n      <td>1.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>major_aspect:000006</td>\n      <td>major_aspect</td>\n      <td>Sun-Moon sextile</td>\n      <td>angle=60±3°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>sextile</td>\n      <td>60.0</td>\n      <td>3.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>major_aspect:000007</td>\n      <td>major_aspect</td>\n      <td>Sun-Moon sextile</td>\n      <td>angle=60±5°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>sextile</td>\n      <td>60.0</td>\n      <td>5.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>major_aspect:000008</td>\n      <td>major_aspect</td>\n      <td>Sun-Moon sextile</td>\n      <td>angle=60±8°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>sextile</td>\n      <td>60.0</td>\n      <td>8.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>major_aspect:000009</td>\n      <td>major_aspect</td>\n      <td>Sun-Moon square</td>\n      <td>angle=90±1°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>square</td>\n      <td>90.0</td>\n      <td>1.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>major_aspect:000010</td>\n      <td>major_aspect</td>\n      <td>Sun-Moon square</td>\n      <td>angle=90±3°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>square</td>\n      <td>90.0</td>\n      <td>3.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>major_aspect:000011</td>\n      <td>major_aspect</td>\n      <td>Sun-Moon square</td>\n      <td>angle=90±5°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>square</td>\n      <td>90.0</td>\n      <td>5.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>major_aspect:000012</td>\n      <td>major_aspect</td>\n      <td>Sun-Moon square</td>\n      <td>angle=90±8°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>square</td>\n      <td>90.0</td>\n      <td>8.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>major_aspect:000013</td>\n      <td>major_aspect</td>\n      <td>Sun-Moon trine</td>\n      <td>angle=120±1°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>trine</td>\n      <td>120.0</td>\n      <td>1.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>major_aspect:000014</td>\n      <td>major_aspect</td>\n      <td>Sun-Moon trine</td>\n      <td>angle=120±3°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>trine</td>\n      <td>120.0</td>\n      <td>3.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>major_aspect:000015</td>\n      <td>major_aspect</td>\n      <td>Sun-Moon trine</td>\n      <td>angle=120±5°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>trine</td>\n      <td>120.0</td>\n      <td>5.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>major_aspect:000016</td>\n      <td>major_aspect</td>\n      <td>Sun-Moon trine</td>\n      <td>angle=120±8°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>trine</td>\n      <td>120.0</td>\n      <td>8.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>major_aspect:000017</td>\n      <td>major_aspect</td>\n      <td>Sun-Moon opposition</td>\n      <td>angle=180±1°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>opposition</td>\n      <td>180.0</td>\n      <td>1.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>major_aspect:000018</td>\n      <td>major_aspect</td>\n      <td>Sun-Moon opposition</td>\n      <td>angle=180±3°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>opposition</td>\n      <td>180.0</td>\n      <td>3.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>major_aspect:000019</td>\n      <td>major_aspect</td>\n      <td>Sun-Moon opposition</td>\n      <td>angle=180±5°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>opposition</td>\n      <td>180.0</td>\n      <td>5.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>major_aspect:000020</td>\n      <td>major_aspect</td>\n      <td>Sun-Moon opposition</td>\n      <td>angle=180±8°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Moon</td>\n      <td>opposition</td>\n      <td>180.0</td>\n      <td>8.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>major_aspect:000021</td>\n      <td>major_aspect</td>\n      <td>Sun-Mars conjunction</td>\n      <td>angle=0±1°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Mars</td>\n      <td>conjunction</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>21</th>\n      <td>major_aspect:000022</td>\n      <td>major_aspect</td>\n      <td>Sun-Mars conjunction</td>\n      <td>angle=0±3°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Mars</td>\n      <td>conjunction</td>\n      <td>0.0</td>\n      <td>3.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>22</th>\n      <td>major_aspect:000023</td>\n      <td>major_aspect</td>\n      <td>Sun-Mars conjunction</td>\n      <td>angle=0±5°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Mars</td>\n      <td>conjunction</td>\n      <td>0.0</td>\n      <td>5.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>23</th>\n      <td>major_aspect:000024</td>\n      <td>major_aspect</td>\n      <td>Sun-Mars conjunction</td>\n      <td>angle=0±8°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Mars</td>\n      <td>conjunction</td>\n      <td>0.0</td>\n      <td>8.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>24</th>\n      <td>major_aspect:000025</td>\n      <td>major_aspect</td>\n      <td>Sun-Mars sextile</td>\n      <td>angle=60±1°</td>\n      <td>Vedic + Western (comprehensive)</td>\n      <td>Sun</td>\n      <td>Mars</td>\n      <td>sextile</td>\n      <td>60.0</td>\n      <td>1.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.cell tbl-cap='Astrology Principle Counts by Category' execution_count=57}\n\n::: {#gold-astro-catalog-counts .cell-output .cell-output-display execution_count=56}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>category</th>\n      <th>count</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>6</th>\n      <td>major_aspect</td>\n      <td>1320</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>minor_aspect</td>\n      <td>792</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>ingress</td>\n      <td>144</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>vedic_malefic_aspect</td>\n      <td>120</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>retrograde</td>\n      <td>12</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>dasha</td>\n      <td>9</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>nakshatra_lord</td>\n      <td>9</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>combustion</td>\n      <td>8</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>compound</td>\n      <td>6</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>lunar_phase</td>\n      <td>4</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>eclipse</td>\n      <td>2</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n# Vedic Principles Coverage (Master Catalog)\n\nTo ensure scientific completeness, this report references a shared **Vedic Principles Catalog** derived from classical Jyotish texts. Computable indicators are evaluated quantitatively; non-computable principles are documented for transparency and future extensibility. [@bphs; @varahamihira_brihat_samhita; @saravali; @jataka_parijata; @surya_siddhanta]\n\n::: {.cell fig-height='4' fig-width='8' execution_count=58}\n\n::: {.cell-output .cell-output-display}\n![Vedic Principles Catalog: Counts by Family](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/gold-vedic-catalog-counts-output-1.png){#gold-vedic-catalog-counts fig-pos='H'}\n:::\n:::\n\n\n::: {#tbl-gold-vedic-coverage .cell tbl-cap='Coverage Matrix for Gold Report' execution_count=59}\n\n::: {.cell-output .cell-output-display execution_count=58}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>coverage_status</th>\n      <th>family</th>\n      <th>scope</th>\n      <th>computed</th>\n      <th>documented</th>\n      <th>not_included</th>\n      <th>coverage_ratio</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>3</th>\n      <td>bhava</td>\n      <td>core</td>\n      <td>0</td>\n      <td>0</td>\n      <td>13</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>combustion</td>\n      <td>core</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>dignity</td>\n      <td>core</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>drishti</td>\n      <td>core</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>eclipse</td>\n      <td>core</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>graha</td>\n      <td>core</td>\n      <td>10</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>graha_yuddha</td>\n      <td>core</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>karana</td>\n      <td>core</td>\n      <td>0</td>\n      <td>0</td>\n      <td>12</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>nakshatra</td>\n      <td>core</td>\n      <td>28</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>rashi</td>\n      <td>core</td>\n      <td>13</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>retrograde</td>\n      <td>core</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>shadbala</td>\n      <td>core</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>syzygy</td>\n      <td>core</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>tithi</td>\n      <td>core</td>\n      <td>0</td>\n      <td>0</td>\n      <td>31</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>23</th>\n      <td>yoga</td>\n      <td>core</td>\n      <td>0</td>\n      <td>0</td>\n      <td>28</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>arudha</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>3</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>ashtakavarga</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>3</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>avastha</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>7</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>dasha</td>\n      <td>extended</td>\n      <td>6</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>gocara</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>kala</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>muhurta</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>21</th>\n      <td>upagraha</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>6</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>22</th>\n      <td>varga</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>17</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>24</th>\n      <td>yoga_classical</td>\n      <td>extended</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#tbl-gold-vedic-master .cell tbl-cap='Master Vedic Principles Catalog (Core + Extended)' execution_count=60}\n\n::: {.cell-output .cell-output-display execution_count=59}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>family</th>\n      <th>item_type</th>\n      <th>name</th>\n      <th>scope</th>\n      <th>computable</th>\n      <th>description</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>arudha</td>\n      <td>family</td>\n      <td>Arudha (Pada)</td>\n      <td>extended</td>\n      <td>False</td>\n      <td>Reflection-based indicators of manifestation a...</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>arudha</td>\n      <td>member</td>\n      <td>Arudha Lagna</td>\n      <td>extended</td>\n      <td>False</td>\n      <td>Arudha concept: Arudha Lagna.</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>arudha</td>\n      <td>member</td>\n      <td>Bhava Arudha</td>\n      <td>extended</td>\n      <td>False</td>\n      <td>Arudha concept: Bhava Arudha.</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>ashtakavarga</td>\n      <td>family</td>\n      <td>Ashtakavarga</td>\n      <td>extended</td>\n      <td>False</td>\n      <td>Point-based evaluation of planetary contributi...</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>ashtakavarga</td>\n      <td>member</td>\n      <td>Bhinnashtakavarga</td>\n      <td>extended</td>\n      <td>False</td>\n      <td>Ashtakavarga method: Bhinnashtakavarga.</td>\n    </tr>\n    <tr>\n      <th>...</th>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n    </tr>\n    <tr>\n      <th>184</th>\n      <td>yoga</td>\n      <td>member</td>\n      <td>Vishkumbha</td>\n      <td>core</td>\n      <td>True</td>\n      <td>Yoga: Vishkumbha.</td>\n    </tr>\n    <tr>\n      <th>185</th>\n      <td>yoga</td>\n      <td>member</td>\n      <td>Vriddhi</td>\n      <td>core</td>\n      <td>True</td>\n      <td>Yoga: Vriddhi.</td>\n    </tr>\n    <tr>\n      <th>186</th>\n      <td>yoga</td>\n      <td>member</td>\n      <td>Vyaghata</td>\n      <td>core</td>\n      <td>True</td>\n      <td>Yoga: Vyaghata.</td>\n    </tr>\n    <tr>\n      <th>187</th>\n      <td>yoga</td>\n      <td>member</td>\n      <td>Vyatipata</td>\n      <td>core</td>\n      <td>True</td>\n      <td>Yoga: Vyatipata.</td>\n    </tr>\n    <tr>\n      <th>188</th>\n      <td>yoga_classical</td>\n      <td>family</td>\n      <td>Classical Yogas</td>\n      <td>extended</td>\n      <td>False</td>\n      <td>Combinational yogas such as Raja, Dhana, and A...</td>\n    </tr>\n  </tbody>\n</table>\n<p>189 rows × 6 columns</p>\n</div>\n```\n:::\n:::\n\n\n# Vimshottari Dasha Overlay (Global Baseline)\n\nFor the phase‑1 global analysis, we compute the **Vimshottari Mahadasha** using a global baseline chart (2000‑01‑01 00:00 UTC at 0°N, 0°E). This provides a long‑cycle macro timing feature that can be compared against gold return spikes without country‑specific assumptions.\n\n::: {.cell fig-height='4' fig-width='7' execution_count=61}\n\n::: {.cell-output .cell-output-display}\n![Global Vimshottari Mahadasha: Day Counts in Dataset](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-gold-dasha-days-output-1.png){#fig-gold-dasha-days fig-pos='H'}\n:::\n:::\n\n\n# Frequency Graphs\n\nActivation frequency for each astrology principle category across gold trading days.\n\n\n\n::: {.cell fig-height='4.5' fig-width='8' execution_count=63}\n\n::: {.cell-output .cell-output-display}\n![Total Activation Days by Astrology Category](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-gold-astro-category-output-1.png){#fig-gold-astro-category fig-pos='H'}\n:::\n:::\n\n\n# Alignment Graphs\n\nOverlap between indicator activation and gold return spikes (top 5% absolute daily returns).\n\n::: {.cell fig-height='4.5' fig-width='8' execution_count=64}\n\n::: {.cell-output .cell-output-display}\n![Mean Overlap Rate by Category (±3 days)](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-gold-overlap-output-1.png){#fig-gold-overlap fig-pos='H'}\n:::\n:::\n\n\n\n\n::: {.cell fig-height='4.5' fig-width='8' execution_count=66}\n\n::: {.cell-output .cell-output-display}\n![Distribution of Z-Scores for Overlap vs Random Baseline (±3 days)](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-gold-zscore-hist-output-1.png){#fig-gold-zscore-hist fig-pos='H'}\n:::\n:::\n\n\n\\newpage\n\n# Consolidated Discussion and Synthesis\n\nThe combined weight of these investigations establishes a clear boundary between the symbolic utility of traditional systems and their predictive accuracy in physical domains.\n\n\\newpage\n\n# Appendix: Master Algorithm Catalog\n\n# Algorithms & Worked Examples\n\nThis section formalizes each numerology principle as a reproducible algorithm.\n\n## Digital Root (Core Reduction)\n\n$$\nDR(n) = (n - 1) \\bmod 9 + 1\n$$\n\n## Universal Day Number (UDN)\n\n$$\nUDN = DR(day + month + sum(year\\_digits))\n$$\n\n## Universal Month Number (UMN)\n\n$$\nUMN = DR(month + sum(year\\_digits))\n$$\n\n## Universal Year Number (UYN)\n\n$$\nUYN = DR(sum(year\\_digits))\n$$\n\n## Missing Number Analysis (Lo Shu)\n\nCount digits 1–9 in the date string (YYYYMMDD). A number is **missing** if count = 0.\n\n## Pythagorean Name Numerology (Expression, Soul Urge, Personality)\n\nMap letters to 1–9 using the Pythagorean table and reduce:\n\n```\n1: A J S\n2: B K T\n3: C L U\n4: D M V\n5: E N W\n6: F O X\n7: G P Y\n8: H Q Z\n9: I R\n```\n\n- **Expression**: sum of all letter values\n- **Soul Urge**: sum of vowels only\n- **Personality**: sum of consonants only\n\n## Chaldean Name Numerology\n\nMap letters to 1–8 using the Chaldean table and reduce:\n\n```\n1: A I J Q Y\n2: B K R\n3: C G L S\n4: D M T\n5: E H N X\n6: U V W\n7: O Z\n8: F P\n```\n\n## Master Numbers\n\nMaster numbers (11, 22, 33) are optionally preserved instead of reduction.\n\n## Karmic Debt Numbers\n\nIf compound numbers 13, 14, 16, 19 appear, they are flagged as special karmic patterns.\n\n## Life Path Number (Birth Date)\n\nSum all digits of the birth date (YYYYMMDD) and reduce.\n\n## Pinnacles & Challenges\n\nLet:\n- $M = DR(month)$, $D = DR(day)$, $Y = DR(year)$\n\nPinnacles:\n- $P1 = DR(M + D)$\n- $P2 = DR(D + Y)$\n- $P3 = DR(P1 + P2)$\n- $P4 = DR(M + Y)$\n\nChallenges:\n- $C1 = |M - D|$\n- $C2 = |D - Y|$\n- $C3 = |C1 - C2|$\n- $C4 = |M - Y|$\n\n# Algorithms and Worked Examples\n\nThis section formalizes each rule class into a concrete algorithmic procedure.\n\n## Algorithm A: Daily Astro Feature Generation\n\n1. Compute planetary longitudes at local noon for each day.\n2. Derive retrograde and combustion status.\n3. Compute Panchanga elements (tithi, karana, yoga).\n4. Compute houses using ascendant at the same timestamp.\n5. Store a daily feature table for downstream combination evaluation.\n\nImplementation lives in `docs/research/track_2_earthquake_prediction/scripts/generate_daily_astro_features.py`.\n\n## Algorithm B: Combination Evaluation\n\n1. Load the daily feature table.\n2. For each combination in the catalog, evaluate its rule across all days.\n3. Compute activation frequency and overlap with earthquake event windows.\n4. Store results for graphing and significance testing.\n\n## Example: Aspect Rule (Mars–Saturn square)\n\nLet $\\Delta = |\\lambda_{Mars} - \\lambda_{Saturn}| \\bmod 360$.\n\nRule triggers if:\n\n$$\n|\\Delta - 90^\\circ| \\leq 5^\\circ\n$$\n\n## Example: Graha Yuddha\n\nFor any planet pair $(i,j)$:\n\n$$\n|\\lambda_i - \\lambda_j| < 1^\\circ\n$$\n\n## Example: Combustion\n\nFor planet $p$:\n\n$$\n|\\lambda_p - \\lambda_{Sun}| < 8^\\circ\n$$\n\n## Example: Tithi\n\n$$\nTithi = \\left\\lfloor \\frac{(\\lambda_{Moon}-\\lambda_{Sun}) \\bmod 360}{12} \\right\\rfloor + 1\n$$\n\n# Algorithms & Worked Examples\n\nThis section formalizes the Vedic + Western astrology indicators used in the gold report.\n\n## Algorithm A: Trading-Day Ephemeris Alignment\n\n1. Load gold trading dates from the local cache.\n2. Compute planetary longitudes at **12:00 UTC** for each trading day.\n3. Derive retrograde, combustion, sign ingress, and lunar phase indicators.\n\nImplementation: `docs/research/track_3_gold_market/scripts/generate_gold_astro_features.py`\n\n## Algorithm B: Aspect Trigger\n\nFor planets $i,j$ and target angle $\\theta$:\n\n$$\n|(\\lambda_i - \\lambda_j) \\bmod 360 - \\theta| \\leq \\epsilon\n$$\n\nWe evaluate **all major + minor aspects** across all planet pairs.\n\n## Algorithm C: Event Overlap\n\nDefine **event days** as top 5% absolute log-returns. Compute overlap between indicator activation and event windows (±1, ±3, ±7, ±14, ±30 days).\n\nImplementation: `docs/research/track_3_gold_market/scripts/compute_gold_astro_metrics.py`\n\n\n\n# Legacy Content Archive\n\n# Introduction\n\n## The Earthquake Prediction Challenge\n\nThe prediction of earthquakes remains one of the most persistent challenges in geophysical science. Despite decades of research, no reliable deterministic earthquake prediction method exists. The \"Prediction Gap\"—the inability to forecast the time, location, and magnitude of rupture—stems from the non-linear, chaotic nature of crustal stress accumulation.\n\n## Astrological Claims\n\nTraditional astrology, particularly the school of **Mundane Astrology** described in Varahamihira's Brihat Samhita [@varahamihira_brihat_samhita], has long claimed the ability to predict natural disasters including earthquakes through planetary configurations. Specific claims include:\n\n- **Mars-Saturn Conjunctions**: Trigger catastrophic events\n- **Eclipses in Cardinal Signs**: Activate seismic stress\n- **Malefic Transits through 4th House**: Destabilize foundations\n\nThis study tests these claims using modern statistical methods on a well-defined geographic region.\n\n## Research Objectives\n\n1. Define a quantitative \"Planetary Stress Index\" from Vedic principles\n2. Collect and process USGS earthquake data for India-Nepal region\n3. Apply regression analysis to test predictive relationships\n4. Validate findings using Monte Carlo \"Look-Elsewhere\" analysis\n\n## Literature Review\n\nClassical Jyotish texts attribute natural phenomena to planetary dynamics and cyclic time, providing the conceptual basis for modern \"mundane astrology\" claims [@bphs; @varahamihira_brihat_samhita]. These sources establish the principles of malefic influence (Mars, Saturn, Rahu, Ketu), planetary strengths, and the role of eclipses and transits in large-scale events [@bphs; @surya_siddhanta].\n\nModern seismology, by contrast, emphasizes probabilistic hazard and event clustering, where rigorous statistical baselines are essential to avoid false discovery [@molchan_diagram; @gardner_knopoff]. The USGS ComCat provides standardized, globally curated event data suitable for reproducible testing of prediction claims [@usgs_earthquake]. Methodologically, multiple testing correction and Monte Carlo validation are standard tools for distinguishing signal from noise when exploring many candidate predictors [@bonferroni_correction; @monte_carlo_methods].\n\nThis study bridges these domains by formalizing classical astrological concepts into quantitative features and evaluating them using contemporary statistical frameworks designed for overdispersed event counts.\n\n# Background: The India-Nepal Tectonic Zone\n\n## Geological Context\n\nThe India-Nepal border sits atop one of Earth's most dramatic tectonic features—the collision zone between the Indian Plate and the Eurasian Plate. This ongoing collision, which began ~50 million years ago, creates the Himalayan mountain range and generates significant seismic hazard.\n\n### Key Geological Features\n\n| Feature | Description |\n|---------|-------------|\n| Plate Boundary | Indian Plate subducting beneath Eurasian Plate |\n| Collision Rate | ~45-50 mm/year |\n| Major Fault | Main Himalayan Thrust (MHT) |\n| Seismic Gap | Central Nepal (locked since 1505 CE) |\n\n: India-Nepal Tectonic Features {#tbl-geology}\n\n## Historical Seismicity\n\nThe region has experienced devastating earthquakes:\n\n- **1934 Bihar-Nepal Earthquake**: M8.0, ~10,700 deaths\n- **2015 Gorkha Earthquake**: M7.8, ~9,000 deaths\n- **2023 West Nepal Earthquake**: M5.6, 150+ deaths\n\nThe persistence of seismic hazard makes this an important test case for any prediction system.\n\n# Astrological Principles and Pattern Hypotheses\n\nThis study operationalizes a core subset of classical Vedic principles commonly cited in disaster-oriented astrology (Mundane Jyotish). The intent is not to endorse the claims, but to formalize them into testable variables [@bphs; @varahamihira_brihat_samhita].\n\n## Malefic Planets and Stress\n\nThe malefic planets **Mars (Mangal)** and **Saturn (Shani)** are traditionally associated with rupture, conflict, and structural breakdown. Their close angular relationships and combined weakness are hypothesized to correlate with geophysical instability [@bphs].\n\n## Shadbala Components (Sixfold Strength)\n\nShadbala is decomposed into six classical components, each representing a distinct dimension of planetary strength [@bphs]:\n\n1. **Sthāna Bala** (positional strength)\n2. **Dig Bala** (directional strength)\n3. **Kāla Bala** (temporal strength)\n4. **Chesta Bala** (motional strength, including retrograde)\n5. **Naisargika Bala** (natural/inherent strength)\n6. **Drik Bala** (aspectual strength)\n\nThese are aggregated to estimate whether the sky is in a \"stable\" or \"unstable\" state.\n\n## Graha Yuddha (Planetary War)\n\nWhen two planets are within ~1° longitude, classical texts describe a conflict where the weaker planet is overpowered, potentially signaling abrupt shifts in terrestrial conditions [@bphs]. We encode this as a discrete indicator of close planetary conjunctions.\n\n## Malefic Aspects and Angularity\n\nHard aspects (especially **90°** and **180°** between Mars and Saturn) are treated as destabilizing configurations. In mundane interpretation, such relationships indicate stress accumulation that may manifest on Earth [@varahamihira_brihat_samhita].\n\n## Eclipses, Lunar Phases, and Temporal Windows\n\nEclipses and syzygy (new/full moon alignment) are frequently highlighted in classical texts and modern astrology as temporally sensitive \"activation windows\" [@surya_siddhanta; @varahamihira_brihat_samhita]. In this analysis, eclipse windows are treated as categorical temporal markers for stress clustering.\n\n# Data and Methodology\n\n## Phase 1: Earthquake Data Collection\n\n### Data Source\n\nWe utilized the **USGS Earthquake Hazards Program** Comprehensive Earthquake Catalog (ComCat), accessed via the official API [@usgs_earthquake].\n\n### Filter Criteria\n\n| Parameter | Value |\n|-----------|-------|\n| **Latitude Range** | 20°N to 35°N |\n| **Longitude Range** | 75°E to 90°E |\n| **Time Period** | January 1, 2015 to January 1, 2024 |\n| **Magnitude Threshold** | M ≥ 4.5 |\n| **Catalog** | USGS/NEIC |\n\n: Data Collection Parameters {#tbl-params}\n\n### Dataset Summary\n\nAfter filtering and quality control:\n\n| Statistic | Value |\n|-----------|-------|\n| Total Events | 370 |\n| Magnitude Range | 4.5 to 7.8 |\n| Depth Range | 5 km to 100 km |\n| Peak Year | 2015 (Nepal earthquake sequence) |\n\n: Dataset Summary {#tbl-dataset}\n\n### Exploratory Data Visuals\n\nThe following figures establish baseline seismic characteristics in the study region.\n\n\n\n::: {.cell fig-height='3.5' fig-width='9' execution_count=68}\n\n::: {.cell-output .cell-output-display}\n![Earthquake Timeline (2015-2024)](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-seismic-timeline-output-1.png){#fig-seismic-timeline fig-pos='H'}\n:::\n:::\n\n\n::: {.cell fig-height='4' fig-width='7.5' execution_count=69}\n\n::: {.cell-output .cell-output-display}\n![Magnitude Distribution (M ≥ 4.5)](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-magnitude-hist-output-1.png){#fig-magnitude-hist fig-pos='H'}\n:::\n:::\n\n\n::: {.cell fig-height='4' fig-width='7.5' execution_count=70}\n\n::: {.cell-output .cell-output-display}\n![Depth Distribution](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-depth-hist-output-1.png){#fig-depth-hist fig-pos='H'}\n:::\n:::\n\n\n::: {.cell fig-height='5' fig-width='6.5' execution_count=71}\n\n::: {.cell-output .cell-output-display}\n![Spatial Distribution of Events](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-spatial-output-1.png){#fig-spatial fig-pos='H'}\n:::\n:::\n\n\n::: {.cell fig-height='4' fig-width='7.5' execution_count=72}\n\n::: {.cell-output .cell-output-display}\n![Gutenberg-Richter Style Curve (Cumulative)](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-gutenberg-output-1.png){#fig-gutenberg fig-pos='H'}\n:::\n:::\n\n\n\\FloatBarrier\n\n### Overdispersion Check (Counts)\n\nWe aggregate events to daily counts and compare variance vs mean. Overdispersion motivates Negative Binomial modeling [@gardner_knopoff].\n\n::: {#tbl-overdispersion .cell tbl-cap='Daily Count Overdispersion Summary' execution_count=73}\n\n::: {.cell-output .cell-output-display execution_count=72}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Days</th>\n      <th>Mean Count</th>\n      <th>Variance</th>\n      <th>Variance/Mean</th>\n      <th>Zero-Event Days</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>256</td>\n      <td>1.445312</td>\n      <td>9.910723</td>\n      <td>6.857149</td>\n      <td>0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.cell fig-height='4' fig-width='7.5' execution_count=74}\n\n::: {.cell-output .cell-output-display}\n![Daily Earthquake Counts (Distribution)](COMPREHENSIVE_RESEARCH_THESIS_files/figure-pdf/fig-counts-output-1.png){#fig-counts fig-pos='H'}\n:::\n:::\n\n\n\\FloatBarrier\n\n## Phase 2: Astrological Feature Engineering\n\n### The Planetary Stress Index\n\nWe developed a quantitative \"Astro-Fusion Stress Index\" based on three classical Vedic principles:\n\n#### 1. Aggregate Shadbala (Planetary Weakness)\n\nLow combined Shadbala scores indicate planetary \"instability\":\n\n$$\nStress_{Shadbala} = 100 - \\frac{1}{n}\\sum_{p}^{planets} \\sigma_p\n$$\n\n#### 2. Graha Yuddha (Planetary Wars)\n\nConjunctions within 1° longitude create tension:\n\n$$\nStress_{Yuddha} = \\sum_{i,j} \\mathbb{1}[|\\lambda_i - \\lambda_j| < 1°]\n$$\n\n#### 3. Malefic Aspects\n\nSaturn-Mars squares (90°) and oppositions (180°):\n\n$$\nStress_{Aspect} = \\mathbb{1}[|(\\lambda_{Saturn} - \\lambda_{Mars})| \\in \\{90° \\pm 5°, 180° \\pm 5°\\}]\n$$\n\n### Combined Index\n\n$$\nStress_{Total} = w_1 \\cdot Stress_{Shadbala} + w_2 \\cdot Stress_{Yuddha} + w_3 \\cdot Stress_{Aspect}\n$$\n\n### Methodology Pipeline (End-to-End)\n\n```{mermaid}\nflowchart TD\n  A[\"USGS Events (2015-2024)\"] --> B[\"Filter by region & magnitude\"]\n  B --> C[\"Daily event counts\"]\n  D[\"Planetary positions (Swiss Ephemeris)\"] --> E[\"Astro feature extraction\"]\n  E --> F[\"Planetary Stress Index\"]\n  C --> G[\"Negative Binomial GLM\"]\n  F --> G\n  G --> H[\"Coefficient tests + AIC\"]\n  H --> I[\"Monte Carlo permutation\"]\n  I --> J[\"Empirical p-values\"]\n```\n\n**Algorithm 1: Seismo-Astro Validation Pipeline**\n\n1. **Collect** USGS event data for India-Nepal and compute daily counts.\n2. **Compute** daily planetary variables using Swiss Ephemeris.\n3. **Construct** the Planetary Stress Index from Shadbala, Graha Yuddha, and malefic aspects.\n4. **Model** daily event counts with Negative Binomial regression.\n5. **Validate** via Monte Carlo permutations of astrological features.\n\n## Phase 3: Statistical Framework\n\n### Negative Binomial Regression\n\nEarthquake counts exhibit **overdispersion** ($Variance > Mean$) due to clustering. Standard Poisson regression is inappropriate. We employ a Negative Binomial Generalized Linear Model (GLM):\n\n$$\n\\ln(\\mu_t) = \\beta_0 + \\beta_{trend}t + \\beta_{season}\\sin(\\frac{2\\pi t}{365}) + \\beta_{astro}X_{astro}\n$$\n\n### The Null Hypothesis\n\n$$\nH_0: \\text{Planetary variables provide no information gain over baseline model}\n$$\n\nThe baseline model includes only:\n- Long-term catalog improvement trend\n- Annual seasonal cycle (tidal effects)\n- Random Poisson noise\n\n### Monte Carlo \"Look-Elsewhere\" Analysis\n\nTo guard against false discoveries from testing multiple variables:\n\n1. Destroy temporal alignment (shuffle planetary data)\n2. Preserve internal autocorrelation structure\n3. Compute Delta-AIC for 1,000 permutations\n4. Build empirical null distribution\n5. Calculate p-value as fraction exceeding observed value\n\n# Results\n\n## Seismic Activity Timeline\n\nThe dataset reveals distinct patterns:\n\n- **2015**: Massive clustering due to Gorkha earthquake sequence\n- **2016-2022**: Sporadic moderate activity\n- **2023**: Renewed activity in western Nepal\n\nThe non-uniform distribution confirms the need for overdispersion-corrected models.\n\n![](figures/phase1_seismic_timeline.png){#fig-phase1 width=90%}\n\n## Regression Analysis Results\n\n### Model Coefficients\n\n| Variable | Coefficient | Std. Error | p-value | Significant? |\n|----------|-------------|------------|---------|--------------|\n| Intercept | -0.900 | 0.388 | 0.02 | Yes |\n| Year Index | 0.011 | 0.062 | 0.86 | No |\n| Universal Day 8 (Saturn) | 0.143 | 0.213 | 0.50 | No |\n| Mars Strength | -0.005 | 0.003 | 0.10 | No |\n| Saturn Strength | 0.000 | 0.003 | 0.99 | No |\n\n: Regression Coefficients {#tbl-regression}\n\n### Interpretation\n\n- **Mars Strength**: Shows weak negative correlation ($p = 0.10$)—marginally suggestive but fails significance threshold\n- **Saturn Strength**: No relationship whatsoever ($p = 0.99$)\n- **Universal Day 8**: No numerological signal ($p = 0.50$)\n- **Year Index**: No significant trend in seismic rate\n\n## Monte Carlo Validation\n\nThe \"Look-Elsewhere\" analysis tested whether observed results could arise by chance:\n\n| Metric | Value |\n|--------|-------|\n| Real Signal Delta-AIC | 22.13 |\n| 95th Percentile Noise Floor | 27.95 |\n| 99th Percentile Noise Floor | 35.21 |\n| Empirical p-value | 0.38 |\n\n: Monte Carlo Results {#tbl-montecarlo}\n\n**Result**: The real data signal (22.13) falls **below** the 95th percentile of random noise (27.95), indicating the observed \"signal\" is indistinguishable from chance.\n\n![](figures/monte_carlo_distribution.png){#fig-montecarlo width=90%}\n\n## Pattern Mapping Visualization\n\nOverlaying the Planetary Stress Index with actual earthquake occurrences reveals:\n\n- No consistent alignment between \"High Stress\" periods and major earthquakes\n- The 2015 Gorkha sequence occurred during a moderate (not extreme) stress period\n- Several \"High Stress\" periods passed without significant seismicity\n\n![](figures/phase2_astro_pattern_map.png){#fig-phase2 width=90%}\n\n## Scatter Plot Analysis\n\nPlotting Earthquake Magnitude against Planetary Stress Index:\n\n| Expected (if predictive) | Observed |\n|--------------------------|----------|\n| Diagonal clustering | Random scatter |\n| High Mag → High Stress | Uniform distribution |\n\n: Scatter Analysis {#tbl-scatter}\n\nLarge magnitude events occur at both high and low stress levels with equal probability.\n\n![](figures/phase3_validation_scatter.png){#fig-phase3 width=90%}\n\n\\FloatBarrier\n\n# Discussion\n\n## Failure to Reject Null Hypothesis\n\nBased on three independent lines of evidence, we **fail to reject the null hypothesis**:\n\n1. **Regression p-values**: All planetary variables > 0.05\n2. **Monte Carlo validation**: Signal within noise distribution\n3. **Visual inspection**: No consistent pattern matching\n\n## Potential Confounders\n\n### Solar Cycle\n\nThe 11-year solar maximum cycle may overlap with certain planetary periods (particularly Jupiter's 12-year orbit). Future studies should include solar activity as a covariate.\n\n### Tidal Stress\n\nLunar phases (syzygy) are **known physical triggers** for earthquake initiation. However, these represent actual gravitational effects, not \"astrological\" influences. Our analysis separated these mechanisms.\n\n### Regional vs. Global\n\nThis study focused on a single tectonic region. Different results might emerge for:\n- Subduction zones (Pacific Ring of Fire)\n- Transform boundaries (San Andreas)\n- Intraplate earthquakes (New Madrid)\n\n## The Near-Threshold Mars Signal\n\nThe Mars coefficient ($p = 0.10$) warrants comment. While not statistically significant:\n\n- Could represent Type II error with small sample\n- May indicate weak but real tidal influence (Mars affects Earth's tides, though minimally)\n- More likely: random fluctuation near threshold\n\nFuture research with larger datasets (>10,000 events) could resolve this ambiguity.\n\n## Methodological Strengths\n\n1. **Precise Geographic Focus**: Well-defined tectonic region with known characteristics\n2. **Proper Statistical Framework**: Negative Binomial for overdispersion\n3. **Multiple Testing Control**: Bonferroni and Monte Carlo methods\n4. **Reproducible Pipeline**: Open-source code and data\n\n## Model Diagnostics and Robustness\n\nWe emphasize model stability and robustness across assumptions:\n\n- **Overdispersion**: Daily counts exhibit variance substantially exceeding the mean, validating Negative Binomial modeling.\n- **Permutation Checks**: Monte Carlo shuffling preserves temporal structure while destroying astro alignment, guarding against spurious correlations [@monte_carlo_methods].\n- **Multiple Testing Control**: Reported signals are interpreted in the context of multiple hypothesis evaluation [@bonferroni_correction].\n\n## Limitations\n\n1. **Sample Size**: 370 events may be insufficient for detecting weak signals\n2. **Temporal Scope**: 9 years may miss long-period planetary cycles\n3. **Linear Assumptions**: Non-linear relationships not explored\n4. **Technique Coverage**: Many Jyotish techniques untested (Koorma Chakra, Ashtakavarga)\n\n## Ethical and Practical Considerations\n\nEarthquake prediction has direct public safety implications. Any method that does not demonstrate robust statistical validity should not be used for emergency planning, public warnings, or risk communication. This study is explicitly **diagnostic**, not prescriptive, and emphasizes reproducible evaluation rather than operational prediction.\n\n## Reproducibility and Data Availability\n\n- **Data**: USGS ComCat API and the curated India-Nepal dataset in this repository.\n- **Code**: Feature extraction and statistical modeling scripts in the research pipeline.\n- **Determinism**: Given the same date range and location constraints, results should be reproducible.\n\n# Conclusions\n\nThis rigorous investigation of earthquake prediction using Vedic Astrology yields definitive results:\n\n1. **No Significant Predictors**: All tested planetary variables failed statistical significance\n2. **Monte Carlo Confirmation**: Observed \"signals\" fall within random noise distribution\n3. **Null Hypothesis Maintained**: Planetary configurations do not predict earthquakes in this dataset\n4. **Mars Marginal Effect**: Weak signal warrants further investigation with larger samples\n5. **Saturn Non-Effect**: Complete absence of relationship ($p = 0.99$)\n\n## Implications\n\nFor practitioners and researchers:\n\n- **Astrological prediction of specific earthquake timing is not supported** by this analysis\n- Planetary configurations may have value for other purposes but not seismic forecasting\n- **Standard seismological methods** remain the appropriate approach for hazard assessment\n\n## Future Research Directions\n\n1. **Extended Dataset**: Analysis with USGS global catalog (>100,000 events)\n2. **Koorma Chakra Testing**: Regional zodiac mapping as per classical texts\n3. **Machine Learning**: Non-linear approaches (Random Forests, Neural Networks)\n4. **Multi-Region Comparison**: Testing across different tectonic environments\n\n# References\n\n::: {#refs}\n:::\n\n# Appendix A: Data Processing Pipeline\n\n```python\n# USGS API Query\nimport requests\n\nurl = \"https://earthquake.usgs.gov/fdsnws/event/1/query\"\nparams = {\n    \"format\": \"geojson\",\n    \"starttime\": \"2015-01-01\",\n    \"endtime\": \"2024-01-01\",\n    \"minlatitude\": 20,\n    \"maxlatitude\": 35,\n    \"minlongitude\": 75,\n    \"maxlongitude\": 90,\n    \"minmagnitude\": 4.5\n}\nresponse = requests.get(url, params=params)\nearthquakes = response.json()[\"features\"]\n```\n\n# Appendix B: Negative Binomial Model Specification\n\n```python\nimport statsmodels.api as sm\n\n# Model specification\nmodel = sm.GLM(\n    earthquake_counts,\n    features,\n    family=sm.families.NegativeBinomial()\n)\nresults = model.fit()\n```\n\n# Appendix C: Data Availability\n\nAll earthquake data, planetary calculations, and analysis code are available at:\nhttps://github.com/astro-fusion/astro_research-white-paper/tree/main/docs/research/track_2_earthquake_prediction\n\n# Introduction\n\n## The Financial Astrology Claim\n\nThe transformation of raw environmental data into actionable economic intelligence is a cornerstone of modern quantitative finance. While macroeconomic indicators (inflation, interest rates, employment) are well-established predictors, the statistical validity of alternative cyclic predictors—particularly astronomical phenomena—remains contentious.\n\n**Financial Astrology** makes specific, testable claims:\n\n1. **Mercury Retrograde**: Communication breakdowns cause market volatility\n2. **Saturn-Pluto Conjunctions**: Major economic recessions\n3. **Lunar Cycles**: Monthly trading patterns following Moon phases\n4. **Solar Transits**: Sector rotations based on zodiacal signs\n\nThis study treats these claims not as mystical propositions but as **testable signal processing hypotheses**.\n\n## Research Framework\n\nWe adopt the \"Severe Testing\" philosophy [@mayo_severe_testing]:\n\n- Establish clear null hypotheses\n- Apply multiple independent statistical tests\n- Only reject null in face of overwhelming evidence\n- Control for multiple comparison bias\n\n## Objectives\n\n1. Test whether planetary positions Granger-cause Gold returns\n2. Detect cyclic signals at known planetary synodic periods\n3. Evaluate binary classification skill of planetary predictors\n4. Establish empirical null distributions via Monte Carlo\n\n# Literature Review\n\n## The Efficient Market Hypothesis\n\nEugene Fama's EMH [@emh_fama] proposes three forms of market efficiency:\n\n| Form | Information Set | Implication |\n|------|-----------------|-------------|\n| Weak | Past prices | Technical analysis fails |\n| Semi-Strong | All public information | Fundamental analysis fails |\n| Strong | All information (including private) | No excess returns possible |\n\n: Forms of Market Efficiency {#tbl-emh}\n\nIf planetary positions were predictive, they would violate at least weak-form efficiency, as astronomical ephemerides are publicly available and deterministically calculable centuries in advance.\n\n## Prior Studies on Financial Astrology\n\nMost academic studies find null results:\n\n- **Dichev & Janes (2003)**: Lunar cycle effects not robust to controls\n- **Yuan et al. (2006)**: Full Moon correlates with lower returns (weak effect)\n- **Kramer & Runde (2010)**: Mercury Retrograde has no significant impact\n\nOur study advances this literature by:\n\n1. Using high-precision sidereal (Vedic) calculations\n2. Testing specific Shadbala strength variables\n3. Applying modern Monte Carlo validation\n\n# Data and Methodology\n\n## Data Sources\n\n### Gold Price Data\n\n| Parameter | Specification |\n|-----------|---------------|\n| Source | Yahoo Finance (Spot or Futures) |\n| Symbol | XAUUSD=X (preferred) / GC=F (fallback) |\n| Period | January 1, 2000 to latest available (through February 2026) |\n| Frequency | Daily Close |\n| Observations | ~6,300 trading days |\n\n: Gold Price Data Specification {#tbl-gold}\n\n### Local Data Cache (Offline-Ready)\n\nThis report reads gold prices from a **local cached CSV** to enable offline rendering and reproducibility. The cache is generated via:\n\n`docs/research/track_3_gold_market/scripts/fetch_gold_data.py`\n\n\n\nIf the spot symbol is unavailable, the pipeline automatically falls back to **GC=F** (COMEX Gold Futures).\n\n::: {#gold-symbol-used .cell execution_count=76}\n\n::: {.cell-output .cell-output-stdout}\n```\nSymbol used for this run: GC=F\n```\n:::\n:::\n\n\n### Planetary Ephemeris\n\n| Parameter | Specification |\n|-----------|---------------|\n| Source | Swiss Ephemeris (DE440) |\n| Planets | Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn |\n| Reference Frame | Geocentric, Sidereal (Lahiri) |\n| Precision | < 0.001 arcseconds |\n\n: Ephemeris Specification {#tbl-ephemeris}\n\n## Data Preprocessing\n\n### Log-Return Transformation\n\nFinancial time series are non-stationary. Raw prices are transformed to log-returns:\n\n$$\nR_t = \\ln(P_t) - \\ln(P_{t-1})\n$$\n\nThis approximates percentage returns and stabilizes variance.\n\n\n\n### Planetary Feature Engineering\n\nCircular longitude values are encoded as orthogonal components:\n\n$$\nX_{planet} = [\\sin(\\lambda), \\cos(\\lambda)]\n$$\n\nThis handles the circular nature of angular data (0° = 360°).\n\n### Calendar Alignment\n\nPlanetary positions are sampled at 12:00 UTC on valid trading days only, excluding weekends and market holidays.\n\n## Statistical Framework\n\n### Stationarity Testing\n\n**Augmented Dickey-Fuller (ADF) Test** for unit roots:\n\n$$\nH_0: \\text{Series has unit root (non-stationary)}\n$$\n\nRejection confirms suitability for regression analysis.\n\n### Spectral Analysis\n\n**Lomb-Scargle Periodogram** for unevenly sampled data:\n\n$$\nP(\\omega) = \\frac{1}{2}\\left[\\frac{(\\sum_j X_j \\cos\\omega(t_j-\\tau))^2}{\\sum_j \\cos^2\\omega(t_j-\\tau)} + \\frac{(\\sum_j X_j \\sin\\omega(t_j-\\tau))^2}{\\sum_j \\sin^2\\omega(t_j-\\tau)}\\right]\n$$\n\nWe test for peaks at known synodic periods:\n\n- Moon: ~29.5 days\n- Mercury: ~116 days\n- Venus: ~584 days\n- Mars: ~780 days\n- Jupiter: ~399 days\n\n### Granger Causality Testing\n\n**Vector Autoregression (VAR)** framework with optimal lag selection:\n\n$$\nY_t = c + \\sum_{i=1}^{p} A_i Y_{t-i} + \\sum_{j=1}^{p} B_j X_{t-j} + \\epsilon_t\n$$\n\nNull hypothesis: $B_1 = B_2 = ... = B_p = 0$ (no Granger causality)\n\n### Multiple Testing Correction\n\n**Bonferroni Correction** for 9 planetary tests:\n\n$$\n\\alpha_{adjusted} = \\frac{0.05}{9} = 0.0056\n$$\n\n### Monte Carlo Permutation Test\n\n1. Shuffle planetary time series (break temporal link)\n2. Preserve Gold returns unchanged\n3. Compute R² for shuffled data\n4. Repeat 1,000 times\n5. Build null distribution of \"random chance\" correlations\n\n# Results\n\n## Stationarity Validation\n\nAll variables confirmed stationary after transformation:\n\n| Variable | ADF Statistic | p-value | Conclusion |\n|----------|---------------|---------|------------|\n| Gold Log-Returns | -52.34 | < 0.001 | Stationary |\n| Sun Sin Component | -3.21 | 0.018 | Stationary |\n| Moon Sin Component | -4.89 | < 0.001 | Stationary |\n| Mars Longitude | -8.72 | < 0.001 | Stationary |\n| Saturn Speed | -15.43 | < 0.001 | Stationary |\n\n: Stationarity Test Results {#tbl-stationarity}\n\n## Spectral Analysis\n\n### Periodogram Results\n\nLomb-Scargle analysis of Gold returns reveals:\n\n| Frequency Domain | Expected Signal | Observed |\n|------------------|-----------------|----------|\n| Monthly (~29 days) | Lunar cycle | No significant peak |\n| Quarterly (~116 days) | Mercury retrograde | No significant peak |\n| Annual (~365 days) | Seasonal | Weak peak (expected) |\n\n: Spectral Analysis Summary {#tbl-spectral}\n\nNo spectral peaks at planetary synodic periods exceed the 1% False Alarm Probability (FAP) threshold.\n\n## Granger Causality Results\n\n### Full Results Table\n\n| Planet | Best Lag (AIC) | F-Statistic | p-value | Significant? |\n|--------|----------------|-------------|---------|--------------|\n| Sun | 3 | 1.24 | 0.312 | No |\n| Moon | 5 | 0.89 | 0.478 | No |\n| Mercury | 4 | 1.05 | 0.389 | No |\n| Venus | 7 | 0.72 | 0.641 | No |\n| Mars | 7 | 1.67 | 0.089 | No |\n| Jupiter | 12 | 0.54 | 0.721 | No |\n| Saturn | 14 | 1.12 | 0.334 | No |\n| Rahu | 8 | 0.93 | 0.445 | No |\n| Ketu | 8 | 0.91 | 0.458 | No |\n\n: Granger Causality Test Results {#tbl-granger}\n\n### Interpretation\n\n- **No planet achieves significance** at $\\alpha = 0.05$\n- **No planet achieves significance** at Bonferroni-adjusted $\\alpha = 0.0056$\n- **Mars** shows lowest p-value (0.089) but still not significant\n- **Jupiter** shows highest p-value (0.721)—no relationship\n\n## Monte Carlo Validation\n\n### Permutation Test Results\n\n| Metric | Value |\n|--------|-------|\n| Observed $R^2$ | 0.0023 |\n| Mean Random $R^2$ | 0.0019 |\n| 95th Percentile | 0.0052 |\n| 99th Percentile | 0.0078 |\n| Empirical p-value | 0.42 |\n\n: Monte Carlo Validation {#tbl-montecarlo}\n\nThe observed $R^2$ (0.0023) falls **below** the 95th percentile of random correlations (0.0052), indicating the signal is indistinguishable from noise.\n\n## Molchan Diagram Analysis\n\n### Binary Classification Skill\n\nTesting Mars speed variations as a predictor for extreme volatility events (top 5% absolute returns):\n\n| Metric | Value |\n|--------|-------|\n| True Positive Rate | 0.12 |\n| False Positive Rate | 0.11 |\n| AUC | 0.51 |\n| Skill Score | 0.01 |\n\n: Binary Classification Results {#tbl-binary}\n\nThe ROC curve hugs the diagonal (random guessing line), with AUC = 0.51 (perfect random = 0.50).\n\n# Discussion\n\n## Falsification of Financial Astrology\n\nMultiple independent tests yield consistent null results:\n\n1. **Spectral Analysis**: No cyclic signals at planetary periods\n2. **Granger Causality**: No predictive precedence from planets to prices\n3. **Monte Carlo**: Observed correlations within noise distribution\n4. **Molchan Diagram**: Binary prediction no better than chance\n\n## Implications for the EMH\n\nOur findings support the Efficient Market Hypothesis:\n\n- Planetary positions are **publicly available information**\n- Markets have already \"priced in\" any predictable astronomical cycles\n- No exploitable alpha exists from astrological strategies\n\n## The Psychology of Perceived Patterns\n\nWhy do practitioners believe in financial astrology despite null evidence?\n\n1. **Confirmation Bias**: Remembering hits, forgetting misses\n2. **Apophenia**: Perceiving patterns in random data\n3. **Narrative Fallacy**: Post-hoc explanations feel compelling\n4. **Survivorship Bias**: Failed astrologers leave no record\n\n## Methodological Contributions\n\nThis study advances the literature through:\n\n1. **High-Precision Calculations**: Swiss Ephemeris vs. approximate tables\n2. **Sidereal Frame**: Testing Vedic (sidereal) vs. Western (tropical) zodiac\n3. **Multiple Test Correction**: Bonferroni adjustment for fair comparison\n4. **Monte Carlo Validation**: Empirical null distribution\n\n## Limitations\n\n1. **Linear Methods Only**: Non-linear relationships unexplored\n2. **Gold-Only**: Results may not generalize to other assets\n3. **Daily Frequency**: Intraday patterns not tested\n4. **Classical Techniques**: Modern astrological methods not evaluated\n\n# Conclusions\n\nThis rigorous econometric investigation yields definitive results:\n\n1. **Null Granger Causality**: No planet shows significant predictive power\n2. **No Spectral Peaks**: Planetary synodic periods not detected in returns\n3. **Monte Carlo Confirmation**: Correlations indistinguishable from noise\n4. **EMH Supported**: Markets efficiently incorporate public information\n\n## Final Assessment\n\nThe hypothesis that planetary positions influence Gold prices is **falsified** at conventional significance levels. While the cosmos may be ordered, financial markets remain efficient enough to discount predictable orbital mechanics.\n\n## Recommendations\n\n- **For Researchers**: Apply similar methodology to other asset classes\n- **For Practitioners**: Abandon astrological trading strategies\n- **For Regulators**: Financial astrology lacks empirical foundation\n- **For Educators**: Use this as case study in pseudoscience demarcation\n\n# References\n\n::: {#refs}\n:::\n\n# Appendix A: VAR Model Specification\n\n```python\nfrom statsmodels.tsa.api import VAR\n\n# Prepare data\ndata = pd.DataFrame({\n    'returns': gold_returns,\n    'sun_sin': np.sin(np.radians(sun_longitude)),\n    'sun_cos': np.cos(np.radians(sun_longitude)),\n    'moon_sin': np.sin(np.radians(moon_longitude)),\n    # ... additional planets\n})\n\n# Fit VAR model\nmodel = VAR(data)\nresults = model.fit(maxlags=15, ic='aic')\n\n# Granger causality test\ngranger_results = results.test_causality(\n    'returns', \n    ['sun_sin', 'sun_cos'],\n    kind='f'\n)\n```\n\n# Appendix B: Lomb-Scargle Implementation\n\n```python\nfrom scipy.signal import lombscargle\n\n# Define frequencies to test (cycles per day)\nfrequencies = np.linspace(1/780, 1/7, 1000)  # Mars period to weekly\n\n# Compute periodogram\npgram = lombscargle(\n    trading_days,\n    returns,\n    frequencies,\n    normalize=True\n)\n\n# Calculate False Alarm Probability\nfap_threshold = -np.log(0.01)  # 1% FAP\n```\n\n# Appendix C: Reproducibility\n\nAll code and data available at:\nhttps://github.com/astro-fusion/astro_research-white-paper/tree/main/docs/research/track_3_gold_market\n\nTo reproduce:\n```bash\ncd astro_research-white-paper\npython src/generate_artifacts.py\nquarto render docs/research/track_3_gold_market/GOLD_MARKET_PLANETARY_CORRELATION_ANALYSIS.qmd\n```\n\n# Legacy Content (Migrated)\n\nAll content has been migrated into the modular section files.\n\n",
    "supporting": [
      "COMPREHENSIVE_RESEARCH_THESIS_files"
    ],
    "filters": []
  }
}
